<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Geocentric models | Rethinking Companion</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Geocentric models | Rethinking Companion" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Geocentric models | Rethinking Companion" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Wade VanderWright" />


<meta name="date" content="2022-09-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sampling-the-imaginary.html"/>
<link rel="next" href="the-many-variables-the-spurious-waffles.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Rethinking Companion</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> url: your book url like <span>https://bookdown.org/yihui/bookdown</span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#statistical-golems"><i class="fa fa-check"></i><b>1.1</b> Statistical golems</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#statistical-rethinking"><i class="fa fa-check"></i><b>1.2</b> Statistical Rethinking</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#what-are-we-trying-to-do-with-the-golems"><i class="fa fa-check"></i><b>1.2.1</b> What are we trying to do with the golems?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#tools-for-golem-engineering"><i class="fa fa-check"></i><b>1.3</b> Tools for golem engineering</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#bayesian-data-analysis"><i class="fa fa-check"></i><b>1.3.1</b> Bayesian data analysis</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#model-comparison-and-predictions"><i class="fa fa-check"></i><b>1.3.2</b> Model comparison and predictions</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#multilevel-models"><i class="fa fa-check"></i><b>1.3.3</b> Multilevel models</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#graphical-causal-models"><i class="fa fa-check"></i><b>1.3.4</b> Graphical causal models</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#summary"><i class="fa fa-check"></i><b>1.4</b> Summary</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#session-info"><i class="fa fa-check"></i>Session Info</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html"><i class="fa fa-check"></i><b>2</b> Small worlds and large worlds</a>
<ul>
<li class="chapter" data-level="2.1" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#the-garden-of-forking-data"><i class="fa fa-check"></i><b>2.1</b> The garden of forking data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#counting-possibilities"><i class="fa fa-check"></i><b>2.1.1</b> Counting possibilities</a></li>
<li class="chapter" data-level="2.1.2" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#combining-other-information"><i class="fa fa-check"></i><b>2.1.2</b> Combining other information</a></li>
<li class="chapter" data-level="2.1.3" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#from-counts-to-probability"><i class="fa fa-check"></i><b>2.1.3</b> From counts to probability</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#building-a-model"><i class="fa fa-check"></i><b>2.2</b> Building a model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#a-data-story"><i class="fa fa-check"></i><b>2.2.1</b> A data story</a></li>
<li class="chapter" data-level="2.2.2" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#bayesian-updating"><i class="fa fa-check"></i><b>2.2.2</b> Bayesian updating</a></li>
<li class="chapter" data-level="2.2.3" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#evaluate"><i class="fa fa-check"></i><b>2.2.3</b> Evaluate</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#components-of-the-model"><i class="fa fa-check"></i><b>2.3</b> Components of the model</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#variables"><i class="fa fa-check"></i><b>2.3.1</b> Variables</a></li>
<li class="chapter" data-level="2.3.2" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#definitions"><i class="fa fa-check"></i><b>2.3.2</b> Definitions</a></li>
<li class="chapter" data-level="2.3.3" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#a-model-is-born"><i class="fa fa-check"></i><b>2.3.3</b> A model is born</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#maiking-the-model-go"><i class="fa fa-check"></i><b>2.4</b> Maiking the model go</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#quadratic"><i class="fa fa-check"></i><b>2.4.1</b> Quadratic</a></li>
<li class="chapter" data-level="2.4.2" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#mcmc"><i class="fa fa-check"></i><b>2.4.2</b> MCMC</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="small-worlds-and-large-worlds.html"><a href="small-worlds-and-large-worlds.html#select-practice-questions"><i class="fa fa-check"></i><b>2.5</b> Select practice questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html"><i class="fa fa-check"></i><b>3</b> Sampling the imaginary</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#probabilities-vs.-frequency-counts"><i class="fa fa-check"></i><b>3.0.1</b> Probabilities vs. Frequency counts</a></li>
<li class="chapter" data-level="3.1" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#sampling-from-a-grid-approximate-posterior"><i class="fa fa-check"></i><b>3.1</b> Sampling from a grid-approximate posterior</a></li>
<li class="chapter" data-level="3.2" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#sampling-to-summarize"><i class="fa fa-check"></i><b>3.2</b> Sampling to summarize</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#intervals-of-defined-boundaries"><i class="fa fa-check"></i><b>3.2.1</b> Intervals of defined boundaries</a></li>
<li class="chapter" data-level="3.2.2" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#intervals-of-defined-mass"><i class="fa fa-check"></i><b>3.2.2</b> intervals of defined mass</a></li>
<li class="chapter" data-level="3.2.3" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#point-estimates"><i class="fa fa-check"></i><b>3.2.3</b> Point estimates</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#sampling-to-simulate-prediction"><i class="fa fa-check"></i><b>3.3</b> Sampling to simulate prediction</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#dummy-data"><i class="fa fa-check"></i><b>3.3.1</b> Dummy data</a></li>
<li class="chapter" data-level="3.3.2" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#model-checking"><i class="fa fa-check"></i><b>3.3.2</b> Model checking</a></li>
<li class="chapter" data-level="3.3.3" data-path="sampling-the-imaginary.html"><a href="sampling-the-imaginary.html#practice-with-brms"><i class="fa fa-check"></i><b>3.3.3</b> Practice with brms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="geocentric-models.html"><a href="geocentric-models.html"><i class="fa fa-check"></i><b>4</b> Geocentric models</a>
<ul>
<li class="chapter" data-level="4.1" data-path="geocentric-models.html"><a href="geocentric-models.html#why-normal-distributions-are-normal"><i class="fa fa-check"></i><b>4.1</b> Why normal distributions are normal</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="geocentric-models.html"><a href="geocentric-models.html#normal-by-addition"><i class="fa fa-check"></i><b>4.1.1</b> Normal by addition</a></li>
<li class="chapter" data-level="4.1.2" data-path="geocentric-models.html"><a href="geocentric-models.html#normal-by-multiplication"><i class="fa fa-check"></i><b>4.1.2</b> Normal by multiplication</a></li>
<li class="chapter" data-level="4.1.3" data-path="geocentric-models.html"><a href="geocentric-models.html#normal-by-log-multiplication"><i class="fa fa-check"></i><b>4.1.3</b> Normal by log-multiplication</a></li>
<li class="chapter" data-level="4.1.4" data-path="geocentric-models.html"><a href="geocentric-models.html#using-gaussian-distributions"><i class="fa fa-check"></i><b>4.1.4</b> Using Gaussian distributions</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="geocentric-models.html"><a href="geocentric-models.html#a-language-for-describing-models"><i class="fa fa-check"></i><b>4.2</b> A language for describing models</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="geocentric-models.html"><a href="geocentric-models.html#re-describing-the-globe-tossing-model."><i class="fa fa-check"></i><b>4.2.1</b> Re-describing the globe tossing model.</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="geocentric-models.html"><a href="geocentric-models.html#gaussian-model-of-height"><i class="fa fa-check"></i><b>4.3</b> Gaussian model of height</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="geocentric-models.html"><a href="geocentric-models.html#the-data"><i class="fa fa-check"></i><b>4.3.1</b> The data</a></li>
<li class="chapter" data-level="4.3.2" data-path="geocentric-models.html"><a href="geocentric-models.html#the-model"><i class="fa fa-check"></i><b>4.3.2</b> The Model</a></li>
<li class="chapter" data-level="4.3.3" data-path="geocentric-models.html"><a href="geocentric-models.html#grid-approximation-of-the-posterior-distribution"><i class="fa fa-check"></i><b>4.3.3</b> Grid approximation of the posterior distribution</a></li>
<li class="chapter" data-level="4.3.4" data-path="geocentric-models.html"><a href="geocentric-models.html#sampling-from-the-posterior"><i class="fa fa-check"></i><b>4.3.4</b> Sampling from the posterior</a></li>
<li class="chapter" data-level="4.3.5" data-path="geocentric-models.html"><a href="geocentric-models.html#finding-the-posterior-distribution-with-quap"><i class="fa fa-check"></i><b>4.3.5</b> Finding the posterior distribution with <code>quap</code></a></li>
<li class="chapter" data-level="4.3.6" data-path="geocentric-models.html"><a href="geocentric-models.html#sampling-with-quap"><i class="fa fa-check"></i><b>4.3.6</b> Sampling with <code>quap</code></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="geocentric-models.html"><a href="geocentric-models.html#linear-prediction"><i class="fa fa-check"></i><b>4.4</b> Linear Prediction</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="geocentric-models.html"><a href="geocentric-models.html#finding-the-posterior-distribtuion"><i class="fa fa-check"></i><b>4.4.1</b> Finding the posterior distribtuion</a></li>
<li class="chapter" data-level="4.4.2" data-path="geocentric-models.html"><a href="geocentric-models.html#interpreting-the-posterior-distribution"><i class="fa fa-check"></i><b>4.4.2</b> Interpreting the posterior distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="geocentric-models.html"><a href="geocentric-models.html#curves-from-lines"><i class="fa fa-check"></i><b>4.5</b> Curves from lines</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="geocentric-models.html"><a href="geocentric-models.html#polynomial-regression"><i class="fa fa-check"></i><b>4.5.1</b> Polynomial regression</a></li>
<li class="chapter" data-level="4.5.2" data-path="geocentric-models.html"><a href="geocentric-models.html#splines"><i class="fa fa-check"></i><b>4.5.2</b> Splines</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html"><i class="fa fa-check"></i><b>5</b> The many variables &amp; the spurious waffles</a>
<ul>
<li class="chapter" data-level="5.1" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#spurious-assoiciation"><i class="fa fa-check"></i><b>5.1</b> Spurious assoiciation</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#think-before-to-regress"><i class="fa fa-check"></i><b>5.1.1</b> Think before to regress</a></li>
<li class="chapter" data-level="5.1.2" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#testable-implications"><i class="fa fa-check"></i><b>5.1.2</b> Testable implications</a></li>
<li class="chapter" data-level="5.1.3" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#multiple-regression-notation"><i class="fa fa-check"></i><b>5.1.3</b> Multiple regression notation</a></li>
<li class="chapter" data-level="5.1.4" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#approximating-the-posterior"><i class="fa fa-check"></i><b>5.1.4</b> Approximating the posterior</a></li>
<li class="chapter" data-level="5.1.5" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#plotting-multivariate-posteriors"><i class="fa fa-check"></i><b>5.1.5</b> Plotting multivariate posteriors</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#masked-relationship"><i class="fa fa-check"></i><b>5.2</b> Masked relationship</a></li>
<li class="chapter" data-level="5.3" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Categorical variables</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#binary-categories"><i class="fa fa-check"></i><b>5.3.1</b> Binary categories</a></li>
<li class="chapter" data-level="5.3.2" data-path="the-many-variables-the-spurious-waffles.html"><a href="the-many-variables-the-spurious-waffles.html#many-categories"><i class="fa fa-check"></i><b>5.3.2</b> Many categories</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html"><i class="fa fa-check"></i><b>6</b> The haunted dag &amp; the casual terror</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#multicollinearity"><i class="fa fa-check"></i><b>6.1</b> Multicollinearity</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#example-try-to-predict-height-from-length-of-a-persons-legs."><i class="fa fa-check"></i><b>6.1.1</b> Example: Try to predict height from length of a person’s legs.</a></li>
<li class="chapter" data-level="6.1.2" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#multicollinear-milk"><i class="fa fa-check"></i><b>6.1.2</b> Multicollinear milk</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#post-treatrment-bias"><i class="fa fa-check"></i><b>6.2</b> Post-treatrment bias</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#a-prior-is-born"><i class="fa fa-check"></i><b>6.2.1</b> A prior is born</a></li>
<li class="chapter" data-level="6.2.2" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#blocked-by-consequence"><i class="fa fa-check"></i><b>6.2.2</b> Blocked by consequence</a></li>
<li class="chapter" data-level="6.2.3" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#fungus-and-d-separation"><i class="fa fa-check"></i><b>6.2.3</b> Fungus and d-separation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#collider-bias"><i class="fa fa-check"></i><b>6.3</b> Collider bias</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#collider-for-false-sorrow"><i class="fa fa-check"></i><b>6.3.1</b> Collider for false sorrow</a></li>
<li class="chapter" data-level="6.3.2" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#the-haunted-dag"><i class="fa fa-check"></i><b>6.3.2</b> The haunted DAG</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#confronting-confounding"><i class="fa fa-check"></i><b>6.4</b> Confronting confounding</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#shutting-the-backdoor"><i class="fa fa-check"></i><b>6.4.1</b> Shutting the backdoor</a></li>
<li class="chapter" data-level="6.4.2" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#two-roads"><i class="fa fa-check"></i><b>6.4.2</b> Two roads</a></li>
<li class="chapter" data-level="6.4.3" data-path="the-haunted-dag-the-casual-terror.html"><a href="the-haunted-dag-the-casual-terror.html#backdoor-waffles"><i class="fa fa-check"></i><b>6.4.3</b> Backdoor waffles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ulysses-compass.html"><a href="ulysses-compass.html"><i class="fa fa-check"></i><b>7</b> Ulysses’ compass</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ulysses-compass.html"><a href="ulysses-compass.html#the-problem-with-parameters"><i class="fa fa-check"></i><b>7.1</b> The problem with parameters</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="ulysses-compass.html"><a href="ulysses-compass.html#more-parameters-almost-always-improve-fit"><i class="fa fa-check"></i><b>7.1.1</b> More parameters (almost) always improve fit</a></li>
<li class="chapter" data-level="7.1.2" data-path="ulysses-compass.html"><a href="ulysses-compass.html#too-few-parameters-hurts-too"><i class="fa fa-check"></i><b>7.1.2</b> Too few parameters hurts, too</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ulysses-compass.html"><a href="ulysses-compass.html#entropy-and-accuracy"><i class="fa fa-check"></i><b>7.2</b> Entropy and accuracy</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ulysses-compass.html"><a href="ulysses-compass.html#firing-the-weatherperson"><i class="fa fa-check"></i><b>7.2.1</b> Firing the weatherperson</a></li>
<li class="chapter" data-level="7.2.2" data-path="ulysses-compass.html"><a href="ulysses-compass.html#information-and-uncertainty"><i class="fa fa-check"></i><b>7.2.2</b> Information and uncertainty</a></li>
<li class="chapter" data-level="7.2.3" data-path="ulysses-compass.html"><a href="ulysses-compass.html#from-entropy-to-accuracy"><i class="fa fa-check"></i><b>7.2.3</b> From entropy to accuracy</a></li>
<li class="chapter" data-level="7.2.4" data-path="ulysses-compass.html"><a href="ulysses-compass.html#estimating-divergence"><i class="fa fa-check"></i><b>7.2.4</b> Estimating divergence</a></li>
<li class="chapter" data-level="7.2.5" data-path="ulysses-compass.html"><a href="ulysses-compass.html#scoring-the-right-data"><i class="fa fa-check"></i><b>7.2.5</b> Scoring the right data</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ulysses-compass.html"><a href="ulysses-compass.html#golem-taming-regularization"><i class="fa fa-check"></i><b>7.3</b> Golem taming: regularization</a></li>
<li class="chapter" data-level="7.4" data-path="ulysses-compass.html"><a href="ulysses-compass.html#predicting-predictive-accuracy"><i class="fa fa-check"></i><b>7.4</b> Predicting predictive accuracy</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ulysses-compass.html"><a href="ulysses-compass.html#cross-validation"><i class="fa fa-check"></i><b>7.4.1</b> Cross-validation</a></li>
<li class="chapter" data-level="7.4.2" data-path="ulysses-compass.html"><a href="ulysses-compass.html#information-criteria"><i class="fa fa-check"></i><b>7.4.2</b> Information criteria</a></li>
<li class="chapter" data-level="7.4.3" data-path="ulysses-compass.html"><a href="ulysses-compass.html#comparing-cv-psis-and-waic"><i class="fa fa-check"></i><b>7.4.3</b> Comparing CV, PSIS, and WAIC</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="ulysses-compass.html"><a href="ulysses-compass.html#model-comparison"><i class="fa fa-check"></i><b>7.5</b> Model comparison</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="ulysses-compass.html"><a href="ulysses-compass.html#model-mis-selection"><i class="fa fa-check"></i><b>7.5.1</b> Model mis-selection</a></li>
<li class="chapter" data-level="7.5.2" data-path="ulysses-compass.html"><a href="ulysses-compass.html#outliers-and-other-illustions"><i class="fa fa-check"></i><b>7.5.2</b> Outliers and other illustions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="conditional-manatees.html"><a href="conditional-manatees.html"><i class="fa fa-check"></i><b>8</b> Conditional manatees</a>
<ul>
<li class="chapter" data-level="8.1" data-path="conditional-manatees.html"><a href="conditional-manatees.html#building-an-interaction"><i class="fa fa-check"></i><b>8.1</b> Building an interaction</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="conditional-manatees.html"><a href="conditional-manatees.html#making-a-rugged-model"><i class="fa fa-check"></i><b>8.1.1</b> Making a rugged model</a></li>
<li class="chapter" data-level="8.1.2" data-path="conditional-manatees.html"><a href="conditional-manatees.html#adding-an-indicator-isnt-enough"><i class="fa fa-check"></i><b>8.1.2</b> Adding an indicator isn’t enough</a></li>
<li class="chapter" data-level="8.1.3" data-path="conditional-manatees.html"><a href="conditional-manatees.html#adding-an-interaction-does-work"><i class="fa fa-check"></i><b>8.1.3</b> Adding an interaction does work</a></li>
<li class="chapter" data-level="8.1.4" data-path="conditional-manatees.html"><a href="conditional-manatees.html#plotting-the-interaction"><i class="fa fa-check"></i><b>8.1.4</b> Plotting the interaction</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="conditional-manatees.html"><a href="conditional-manatees.html#symmetry-of-interactions"><i class="fa fa-check"></i><b>8.2</b> Symmetry of interactions</a></li>
<li class="chapter" data-level="8.3" data-path="conditional-manatees.html"><a href="conditional-manatees.html#continuous-interactions"><i class="fa fa-check"></i><b>8.3</b> Continuous interactions</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="conditional-manatees.html"><a href="conditional-manatees.html#a-winter-flower"><i class="fa fa-check"></i><b>8.3.1</b> A winter flower</a></li>
<li class="chapter" data-level="8.3.2" data-path="conditional-manatees.html"><a href="conditional-manatees.html#the-models"><i class="fa fa-check"></i><b>8.3.2</b> the models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="markov-chain-monte-carlo.html"><a href="markov-chain-monte-carlo.html"><i class="fa fa-check"></i><b>9</b> Markov chain monte carlo</a></li>
<li class="chapter" data-level="10" data-path="big-entropy-and-the-generalized-linear-model.html"><a href="big-entropy-and-the-generalized-linear-model.html"><i class="fa fa-check"></i><b>10</b> Big entropy and the generalized linear model</a></li>
<li class="chapter" data-level="11" data-path="god-spiked-the-integers.html"><a href="god-spiked-the-integers.html"><i class="fa fa-check"></i><b>11</b> God spiked the integers</a></li>
<li class="chapter" data-level="12" data-path="monsters-and-mixtures.html"><a href="monsters-and-mixtures.html"><i class="fa fa-check"></i><b>12</b> Monsters and mixtures</a></li>
<li class="chapter" data-level="13" data-path="models-with-memory.html"><a href="models-with-memory.html"><i class="fa fa-check"></i><b>13</b> Models with memory</a></li>
<li class="chapter" data-level="14" data-path="adventures-in-covariance.html"><a href="adventures-in-covariance.html"><i class="fa fa-check"></i><b>14</b> Adventures in covariance</a></li>
<li class="chapter" data-level="15" data-path="missing-data-and-other-opportunities.html"><a href="missing-data-and-other-opportunities.html"><i class="fa fa-check"></i><b>15</b> Missing data and other opportunities</a></li>
<li class="chapter" data-level="16" data-path="generalized-linear-madness.html"><a href="generalized-linear-madness.html"><i class="fa fa-check"></i><b>16</b> Generalized linear madness</a></li>
<li class="chapter" data-level="17" data-path="horoscopes.html"><a href="horoscopes.html"><i class="fa fa-check"></i><b>17</b> Horoscopes</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Rethinking Companion</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="geocentric-models" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Geocentric models<a href="geocentric-models.html#geocentric-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<blockquote>
<p>This chapter introduces linear regression as a Bayesian procedure. Under a probability interpretation, which is necessary for Bayesian work, linear regression uses a Gaussian (normal) distribution to describe our golem’s uncertainty about some measurement of interest. This type of model is simple, flexible, and commonplace. Like all statistical models, it is not universally useful. But linear regression has a strong claim to being foundational, in the sense that once you learn to build and interpret linear regression models, you can more easily move on to other types of regression which are less normal.
&gt;p. 71</p>
</blockquote>
<div id="why-normal-distributions-are-normal" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Why normal distributions are normal<a href="geocentric-models.html#why-normal-distributions-are-normal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Imagine there are 1000 people standing on the center line of a soccer field and they each have a coin. They each toss their coin 16 times and with each toss, heads means one step left, and tails means one step right. After everyone has done their 16 tosses, can you imagine the distribution of where they would be on the field? It would be roughly normal centered on the center of the field.</p>
<div id="normal-by-addition" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Normal by addition<a href="geocentric-models.html#normal-by-addition" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To simulate this in R we can assign random values that are either left (-1) or right (1) for each coin toss and then add them together.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="geocentric-models.html#cb1-1" aria-hidden="true" tabindex="-1"></a>pos <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">sum</span>(<span class="fu">runif</span>(<span class="dv">16</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)))</span>
<span id="cb1-2"><a href="geocentric-models.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="geocentric-models.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(pos))</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.1-1.png" width="672" />
Now lets visualize what each person’s walk</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="geocentric-models.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load packages</span></span>
<span id="cb2-2"><a href="geocentric-models.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="geocentric-models.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb6-2"><a href="geocentric-models.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.1.2</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="geocentric-models.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set seed for reproducible plots</span></span>
<span id="cb8-2"><a href="geocentric-models.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb8-3"><a href="geocentric-models.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#create dataframe</span></span>
<span id="cb8-4"><a href="geocentric-models.html#cb8-4" aria-hidden="true" tabindex="-1"></a>pos_df <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">runif</span>(<span class="dv">16</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span> <span class="co">#simulation (turned down to 100 people)</span></span>
<span id="cb8-5"><a href="geocentric-models.html#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> <span class="co"># make it a tibble</span></span>
<span id="cb8-6"><a href="geocentric-models.html#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(<span class="dv">0</span>, .) <span class="sc">%&gt;%</span> <span class="co"># add a row of zeros above the coin tosses as a starting point</span></span>
<span id="cb8-7"><a href="geocentric-models.html#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">step =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">16</span>) <span class="sc">%&gt;%</span> <span class="co">#this is the step index</span></span>
<span id="cb8-8"><a href="geocentric-models.html#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(key, value, <span class="sc">-</span>step) <span class="sc">%&gt;%</span> <span class="co">#this will convert the data into long format</span></span>
<span id="cb8-9"><a href="geocentric-models.html#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">person =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="at">each =</span> <span class="dv">17</span>)) <span class="sc">%&gt;%</span>  <span class="co">#this adds a person index (17 times for the 0 and 16 coins)</span></span>
<span id="cb8-10"><a href="geocentric-models.html#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(person) <span class="sc">%&gt;%</span> <span class="co">#for each person value</span></span>
<span id="cb8-11"><a href="geocentric-models.html#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">position =</span> <span class="fu">cumsum</span>(value)) <span class="sc">%&gt;%</span> <span class="co">#create a cumulative sum for each person</span></span>
<span id="cb8-12"><a href="geocentric-models.html#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
## Using compatibility `.name_repair`.</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="geocentric-models.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create plot</span></span>
<span id="cb10-2"><a href="geocentric-models.html#cb10-2" aria-hidden="true" tabindex="-1"></a>pos_df <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="geocentric-models.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> step, <span class="at">y =</span> position, <span class="at">group =</span> person)) <span class="sc">+</span></span>
<span id="cb10-4"><a href="geocentric-models.html#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">16</span>), <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="geocentric-models.html#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> person <span class="sc">&lt;</span> <span class="dv">2</span>, <span class="at">alpha =</span> person <span class="sc">&lt;</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb10-6"><a href="geocentric-models.html#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;skyblue4&#39;</span>,<span class="st">&#39;black&#39;</span>)) <span class="sc">+</span></span>
<span id="cb10-7"><a href="geocentric-models.html#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_alpha_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>, <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb10-8"><a href="geocentric-models.html#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">&#39;step number&#39;</span>, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb10-9"><a href="geocentric-models.html#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&#39;none&#39;</span>,</span>
<span id="cb10-10"><a href="geocentric-models.html#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>You can see that the more steps you add, the more normal the distribution becomes.</p>
</div>
<div id="normal-by-multiplication" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Normal by multiplication<a href="geocentric-models.html#normal-by-multiplication" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose that an organism’s growth rate is influenced by 12 loci each with several alleles that code for more growth and that these loci can interact with each other causing multiplicative effects</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="geocentric-models.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb11-2"><a href="geocentric-models.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>, <span class="dv">0</span>, <span class="fl">0.1</span>))</span></code></pre></div>
<pre><code>## [1] 1.448587</code></pre>
<p>Or more explicitly:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="geocentric-models.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb13-2"><a href="geocentric-models.html#cb13-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb13-3"><a href="geocentric-models.html#cb13-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">=</span> <span class="fu">runif</span>(<span class="dv">12</span>, <span class="dv">0</span>, <span class="fl">0.1</span>)</span>
<span id="cb13-4"><a href="geocentric-models.html#cb13-4" aria-hidden="true" tabindex="-1"></a>c <span class="ot">=</span> a <span class="sc">+</span> b</span>
<span id="cb13-5"><a href="geocentric-models.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(c)</span></code></pre></div>
<pre><code>## [1] 1.448587</code></pre>
<p>as a density:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="geocentric-models.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb15-2"><a href="geocentric-models.html#cb15-2" aria-hidden="true" tabindex="-1"></a>growth <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>, <span class="dv">0</span>, <span class="fl">0.1</span>)))</span>
<span id="cb15-3"><a href="geocentric-models.html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(growth))</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.3-1.png" width="672" /></p>
<p>Now see how the distribution behaves if you change the effect size of the loci</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="geocentric-models.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb16-2"><a href="geocentric-models.html#cb16-2" aria-hidden="true" tabindex="-1"></a>big <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>, <span class="dv">0</span>, <span class="fl">0.5</span>)))</span>
<span id="cb16-3"><a href="geocentric-models.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(big))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="geocentric-models.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb17-2"><a href="geocentric-models.html#cb17-2" aria-hidden="true" tabindex="-1"></a>small <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>, <span class="dv">0</span>, <span class="fl">0.01</span>)))</span>
<span id="cb17-3"><a href="geocentric-models.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(small))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="normal-by-log-multiplication" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Normal by log-multiplication<a href="geocentric-models.html#normal-by-log-multiplication" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>See how skewed the <code>big</code> distribution was above? If we log transform the product, what do you think we will see?</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="geocentric-models.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb18-2"><a href="geocentric-models.html#cb18-2" aria-hidden="true" tabindex="-1"></a>log_big <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">log</span>(<span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>, <span class="dv">0</span>, <span class="fl">0.5</span>))))</span>
<span id="cb18-3"><a href="geocentric-models.html#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(log_big))</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.5-1.png" width="672" /></p>
</div>
<div id="using-gaussian-distributions" class="section level3 hasAnchor" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Using Gaussian distributions<a href="geocentric-models.html#using-gaussian-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>define ontological</p>
<p>define epistemological</p>
</div>
</div>
<div id="a-language-for-describing-models" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> A language for describing models<a href="geocentric-models.html#a-language-for-describing-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Learning the language
1. Recognize the variables you are working with. Observable variables are <em>data</em> and unobservable variables are parameters<br />
2. Define the variable in terms of the other variables or as probability distributions<br />
3. The combination of variables and probability distributions are <em>joint generative models</em> that can be used to simulate hypothetical observations as well as analyze real ones<br />
</p>
<p>Summarize the model in a mathy way:<br />
</p>
<p><span class="math display">\[\begin{equation}
    y_{i} ~ \text{Normal}(\mu_{i}, \sigma)\
    \mu_{i} ~ \beta x_{i}\
    \beta ~ \text{Normal}(0, 10)\
    \sigma ~ \text{Exponential}(1)\
    x_{i} ~ \text{Normal}(0,1)\
\end{equation}\]</span></p>
<div id="re-describing-the-globe-tossing-model." class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Re-describing the globe tossing model.<a href="geocentric-models.html#re-describing-the-globe-tossing-model." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that the globe tossing model had the variables defined as:<br />
</p>
<p><span class="math display">\[\begin{equation}
W ~ \text{Binomial}(N, p)\
p ~ \text{Uniform}(0, 1)
\end{equation}\]</span></p>
<p>These definitions have implied meanings. For example, the Binomial distribution of <span class="math inline">\(W\)</span> implies that each toss (<span class="math inline">\(N\)</span>) is independent of the others. The first line of these simple models are the likelihood function from Bayes’ theorem. The other lines will outline priors for variables if defined.</p>
</div>
</div>
<div id="gaussian-model-of-height" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Gaussian model of height<a href="geocentric-models.html#gaussian-model-of-height" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we will build the beginnings of a regression model that will follow a gaussian distribution with a mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>. The model will take in data or a predictor variable and evaluate all possible values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> to produce a distribution of distributions basically.</p>
<div id="the-data" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> The data<a href="geocentric-models.html#the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s load up McElreath’s data</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="geocentric-models.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rethinking)</span></code></pre></div>
<pre><code>## Loading required package: rstan</code></pre>
<pre><code>## Warning: package &#39;rstan&#39; was built under R version 4.1.2</code></pre>
<pre><code>## Loading required package: StanHeaders</code></pre>
<pre><code>## rstan (Version 2.21.7, GitRev: 2e1f913d3ca3)</code></pre>
<pre><code>## For execution on a local, multicore CPU with excess RAM we recommend calling
## options(mc.cores = parallel::detectCores()).
## To avoid recompilation of unchanged Stan programs, we recommend calling
## rstan_options(auto_write = TRUE)</code></pre>
<pre><code>## 
## Attaching package: &#39;rstan&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:tidyr&#39;:
## 
##     extract</code></pre>
<pre><code>## Loading required package: cmdstanr</code></pre>
<pre><code>## Warning: package &#39;cmdstanr&#39; was built under R version 4.1.3</code></pre>
<pre><code>## This is cmdstanr version 0.5.3</code></pre>
<pre><code>## - CmdStanR documentation and vignettes: mc-stan.org/cmdstanr</code></pre>
<pre><code>## - Use set_cmdstan_path() to set the path to CmdStan</code></pre>
<pre><code>## - Use install_cmdstan() to install CmdStan</code></pre>
<pre><code>## Loading required package: parallel</code></pre>
<pre><code>## rethinking (Version 2.21)</code></pre>
<pre><code>## 
## Attaching package: &#39;rethinking&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:rstan&#39;:
## 
##     stan</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     rstudent</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="geocentric-models.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Howell1)</span>
<span id="cb38-2"><a href="geocentric-models.html#cb38-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> Howell1</span></code></pre></div>
<p>Now we can see the new data frame</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="geocentric-models.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(d)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    544 obs. of  4 variables:
##  $ height: num  152 140 137 157 145 ...
##  $ weight: num  47.8 36.5 31.9 53 41.3 ...
##  $ age   : num  63 63 65 41 51 35 32 27 19 54 ...
##  $ male  : int  1 0 0 1 0 1 0 1 0 1 ...</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="geocentric-models.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(d, <span class="at">hist=</span><span class="cn">FALSE</span>) <span class="co">#rethinking package</span></span></code></pre></div>
<pre><code>##               mean         sd      5.5%     94.5%
## height 138.2635963 27.6024476 81.108550 165.73500
## weight  35.6106176 14.7191782  9.360721  54.50289
## age     29.3443934 20.7468882  1.000000  66.13500
## male     0.4724265  0.4996986  0.000000   1.00000</code></pre>
<p>And for this model we will just be using height of adults</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="geocentric-models.html#cb43-1" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d[d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span> ,] <span class="co">#create a new data frame that is all rows where age is 18 or greater</span></span></code></pre></div>
</div>
<div id="the-model" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> The Model<a href="geocentric-models.html#the-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We want to model these heights with a Gaussian distribution. Let’s see the data first</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="geocentric-models.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(d2<span class="sc">$</span>height)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.11-1.png" width="672" /></p>
<p>This is pretty normal looking so we can go ahead and set the model up to use a Gaussian distirbution to describe the probability distribution of the data. Because we are still unsure about which distribution is the right one, we will leave the mean and standard deviation as variables for now.<br />
</p>
<p><span class="math display">\[\begin{equation}
h_i ~ \text{Normal}(\mu, \sigma)
\end{equation}\]</span></p>
<p>This is our likelihood function for the model. Next we will need to define our <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> variables.</p>
<p><span class="math display">\[\begin{equation}
\mu ~ \text{Normal}(178, 20)
\sigma ~ \text{Uniform}(0, 50)
\end{equation}\]</span></p>
<p>Here McElreath uses 178 cm as the mean because that is his height and spreads the 95% interval 40 cm in either direction (138 - 218cm). Let’s see what this would look like</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="geocentric-models.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="dv">178</span>, <span class="dv">20</span>), <span class="at">from =</span> <span class="dv">100</span>, <span class="at">to =</span> <span class="dv">250</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.12-1.png" width="672" /></p>
<p>Here we are looking across heights from 100cm to 250cm and as you can see the normal distribution is putting the the mean between 140 and 220.</p>
<p><span class="math inline">\(\sigma\)</span> has a uniform prior that holds its value somewhere between 0 and 50 cm.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="geocentric-models.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dunif</span>(x, <span class="dv">0</span>, <span class="dv">50</span>), <span class="at">from =</span> <span class="sc">-</span><span class="dv">10</span>, <span class="at">to =</span> <span class="dv">60</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.13-1.png" width="672" /></p>
<p>Here you can see that any value from 0 to 50 has an equal probability of being ‘correct.’ Now we can create something called a <em>Prior Predictive</em> by using the priors we’ve defined to see how they relate to the observed heights.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="geocentric-models.html#cb47-1" aria-hidden="true" tabindex="-1"></a>sample_mu <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fl">1e4</span>, <span class="dv">178</span>, <span class="dv">20</span>) <span class="co">#create randome draws from the mu prior</span></span>
<span id="cb47-2"><a href="geocentric-models.html#cb47-2" aria-hidden="true" tabindex="-1"></a>sample_sigma <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fl">1e4</span>, <span class="dv">0</span>, <span class="dv">50</span>) <span class="co">#create random draws from the sigma prior</span></span>
<span id="cb47-3"><a href="geocentric-models.html#cb47-3" aria-hidden="true" tabindex="-1"></a>prior_h <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fl">1e4</span>, sample_mu, sample_sigma) <span class="co">#use the priors of mu and sigma to infulence h</span></span>
<span id="cb47-4"><a href="geocentric-models.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(prior_h)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.14-1.png" width="672" /></p>
</div>
<div id="grid-approximation-of-the-posterior-distribution" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Grid approximation of the posterior distribution<a href="geocentric-models.html#grid-approximation-of-the-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here we will approximate the posterior in detail with grid approximation for learning purposes. First will be the methods presented by McElreath and second I will add a tidyverse version adapted from <a href="https://bookdown.org/ajkurz/Statistical_Rethinking_recoded/linear-models.html">Kurz</a></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="geocentric-models.html#cb48-1" aria-hidden="true" tabindex="-1"></a>mu_list <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">150</span>, <span class="at">to =</span> <span class="dv">160</span>, <span class="at">length.out =</span> <span class="dv">100</span>) <span class="co">#100 equally spaced values from 150 to 160</span></span>
<span id="cb48-2"><a href="geocentric-models.html#cb48-2" aria-hidden="true" tabindex="-1"></a>sigma_list <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">7</span>, <span class="at">to =</span> <span class="dv">9</span>, <span class="at">length.out =</span> <span class="dv">100</span>) <span class="co">#100 equally spaced values from 7 to 9</span></span>
<span id="cb48-3"><a href="geocentric-models.html#cb48-3" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">mu =</span> mu_list, <span class="at">sigma =</span> sigma_list) <span class="co">#expand to a grid of all combinations of the above (100 x 100)</span></span>
<span id="cb48-4"><a href="geocentric-models.html#cb48-4" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>LL <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(post), <span class="cf">function</span>(i) <span class="fu">sum</span>(</span>
<span id="cb48-5"><a href="geocentric-models.html#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dnorm</span>(d2<span class="sc">$</span>height, post<span class="sc">$</span>mu[i], post<span class="sc">$</span>sigma[i], <span class="at">log =</span> <span class="cn">TRUE</span>))) <span class="co">#calculate the log likelihood for each row of post across the data values of d2$height</span></span>
<span id="cb48-6"><a href="geocentric-models.html#cb48-6" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>prod <span class="ot">&lt;-</span> post<span class="sc">$</span>LL <span class="sc">+</span> <span class="fu">dnorm</span>(post<span class="sc">$</span>mu, <span class="dv">178</span>, <span class="dv">20</span>, <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">dunif</span>(post<span class="sc">$</span>sigma, <span class="dv">0</span>, <span class="dv">50</span>, <span class="cn">TRUE</span>) <span class="co">#create a product by adding priors to log likelihood</span></span>
<span id="cb48-7"><a href="geocentric-models.html#cb48-7" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="fu">exp</span>(post<span class="sc">$</span>prod <span class="sc">-</span> <span class="fu">max</span>(post<span class="sc">$</span>prod)) <span class="co">#Create the posterior probability by taking each product and subtracting the maximum product (while also back transforming to cm)</span></span></code></pre></div>
<p>Now we can see the posterior with:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="geocentric-models.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contour_xyz</span>(post<span class="sc">$</span>mu, post<span class="sc">$</span>sigma, post<span class="sc">$</span>prob)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.17-1.png" width="672" /></p>
<p>or:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="geocentric-models.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">image_xyz</span>(post<span class="sc">$</span>mu, post<span class="sc">$</span>sigma, post<span class="sc">$</span>prob)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.18-1.png" width="672" /></p>
<p>In tidyverse language</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="geocentric-models.html#cb51-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb51-2"><a href="geocentric-models.html#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="geocentric-models.html#cb51-3" aria-hidden="true" tabindex="-1"></a>d_grid <span class="ot">&lt;-</span> </span>
<span id="cb51-4"><a href="geocentric-models.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(mu <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">150</span>, <span class="at">to =</span> <span class="dv">160</span>, <span class="at">length.out =</span> n),</span>
<span id="cb51-5"><a href="geocentric-models.html#cb51-5" aria-hidden="true" tabindex="-1"></a>         sigma <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">7</span>, <span class="at">to =</span> <span class="dv">9</span>, <span class="at">length.out =</span> n)) </span>
<span id="cb51-6"><a href="geocentric-models.html#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="geocentric-models.html#cb51-7" aria-hidden="true" tabindex="-1"></a>d_grid <span class="ot">&lt;-</span> d_grid <span class="sc">%&gt;%</span> </span>
<span id="cb51-8"><a href="geocentric-models.html#cb51-8" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">expand</span>(mu, sigma)</span>
<span id="cb51-9"><a href="geocentric-models.html#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="geocentric-models.html#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d_grid)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##      mu sigma
##   &lt;dbl&gt; &lt;dbl&gt;
## 1   150  7   
## 2   150  7.02
## 3   150  7.04
## 4   150  7.06
## 5   150  7.08
## 6   150  7.10</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="geocentric-models.html#cb53-1" aria-hidden="true" tabindex="-1"></a>grid_function <span class="ot">&lt;-</span> <span class="cf">function</span>(mu, sigma){</span>
<span id="cb53-2"><a href="geocentric-models.html#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dnorm</span>(d2<span class="sc">$</span>height, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma, <span class="at">log =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="geocentric-models.html#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>()</span>
<span id="cb53-4"><a href="geocentric-models.html#cb53-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-5"><a href="geocentric-models.html#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="geocentric-models.html#cb53-6" aria-hidden="true" tabindex="-1"></a>d_grid <span class="ot">&lt;-</span> d_grid <span class="sc">%&gt;%</span> </span>
<span id="cb53-7"><a href="geocentric-models.html#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_likelihood =</span> purrr<span class="sc">::</span><span class="fu">map2</span>(mu, sigma, grid_function)) <span class="sc">%&gt;%</span> </span>
<span id="cb53-8"><a href="geocentric-models.html#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb53-9"><a href="geocentric-models.html#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prior_mu =</span> <span class="fu">dnorm</span>(mu, <span class="at">mean =</span> <span class="dv">178</span>, <span class="at">sd =</span> <span class="dv">20</span>, <span class="at">log =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-10"><a href="geocentric-models.html#cb53-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">prior_sigma =</span> <span class="fu">dunif</span>(sigma, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">50</span>, <span class="at">log =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb53-11"><a href="geocentric-models.html#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">product =</span> log_likelihood <span class="sc">+</span> prior_mu <span class="sc">+</span> prior_sigma) <span class="sc">%&gt;%</span> </span>
<span id="cb53-12"><a href="geocentric-models.html#cb53-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">probability =</span> <span class="fu">exp</span>(product <span class="sc">-</span> <span class="fu">max</span>(product)))</span></code></pre></div>
<pre><code>## Warning: `cols` is now required when using unnest().
## Please use `cols = c(log_likelihood)`</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="geocentric-models.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d_grid)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 7
##      mu sigma log_likelihood prior_mu prior_sigma product probability
##   &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;
## 1   150  7            -1299.    -4.89       -3.91  -1308.    1.96e-35
## 2   150  7.02         -1298.    -4.89       -3.91  -1307.    3.78e-35
## 3   150  7.04         -1298.    -4.89       -3.91  -1307.    7.20e-35
## 4   150  7.06         -1297.    -4.89       -3.91  -1306.    1.36e-34
## 5   150  7.08         -1296.    -4.89       -3.91  -1305.    2.53e-34
## 6   150  7.10         -1296.    -4.89       -3.91  -1305.    4.65e-34</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="geocentric-models.html#cb57-1" aria-hidden="true" tabindex="-1"></a>d_grid <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="geocentric-models.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> sigma, <span class="at">z =</span> probability)) <span class="sc">+</span></span>
<span id="cb57-3"><a href="geocentric-models.html#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour</span>() <span class="sc">+</span></span>
<span id="cb57-4"><a href="geocentric-models.html#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu),</span>
<span id="cb57-5"><a href="geocentric-models.html#cb57-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="fu">expression</span>(sigma)) <span class="sc">+</span></span>
<span id="cb57-6"><a href="geocentric-models.html#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">range</span>(d_grid<span class="sc">$</span>mu)) <span class="sc">+</span></span>
<span id="cb57-7"><a href="geocentric-models.html#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">range</span>(d_grid<span class="sc">$</span>sigma)) <span class="sc">+</span></span>
<span id="cb57-8"><a href="geocentric-models.html#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="geocentric-models.html#cb58-1" aria-hidden="true" tabindex="-1"></a>d_grid <span class="sc">%&gt;%</span> </span>
<span id="cb58-2"><a href="geocentric-models.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> sigma)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="geocentric-models.html#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">fill =</span> probability), <span class="at">interpolate =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb58-4"><a href="geocentric-models.html#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">&#39;A&#39;</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a href="geocentric-models.html#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu),</span>
<span id="cb58-6"><a href="geocentric-models.html#cb58-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="fu">expression</span>(sigma)) <span class="sc">+</span></span>
<span id="cb58-7"><a href="geocentric-models.html#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="sampling-from-the-posterior" class="section level3 hasAnchor" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> Sampling from the posterior<a href="geocentric-models.html#sampling-from-the-posterior" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have a posterior calculated, we can pull samples from it.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="geocentric-models.html#cb59-1" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(post), <span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> post<span class="sc">$</span>prob) <span class="co">#sample rows by their probability</span></span>
<span id="cb59-2"><a href="geocentric-models.html#cb59-2" aria-hidden="true" tabindex="-1"></a>sample_mu <span class="ot">&lt;-</span> post<span class="sc">$</span>mu[sample_rows] <span class="co">#index samples of mu by the rows sampled</span></span>
<span id="cb59-3"><a href="geocentric-models.html#cb59-3" aria-hidden="true" tabindex="-1"></a>sample_sigma <span class="ot">&lt;-</span> post<span class="sc">$</span>sigma[sample_rows] <span class="co">#index samples of sigma by rows sampled</span></span></code></pre></div>
<p>Now we can plot these samples to see where the most common values for <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> might overlap</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="geocentric-models.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_mu, sample_sigma, <span class="at">cex =</span> <span class="dv">1</span>, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.1</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.20-1.png" width="672" /></p>
<p>We can also look at the samples individually</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="geocentric-models.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(sample_mu)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.21-1.png" width="672" /></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="geocentric-models.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(sample_sigma)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.21-2.png" width="672" /></p>
<p>And we can get summary points from these sample distributions just like before</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="geocentric-models.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(sample_mu)</span></code></pre></div>
<pre><code>##       5%      94% 
## 153.9394 155.2525</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="geocentric-models.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(sample_sigma)</span></code></pre></div>
<pre><code>##       5%      94% 
## 7.323232 8.252525</code></pre>
<p>(tidyverse)</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="geocentric-models.html#cb67-1" aria-hidden="true" tabindex="-1"></a>d_grid_samples <span class="ot">&lt;-</span> d_grid <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="geocentric-models.html#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">weight =</span> probability)</span>
<span id="cb67-3"><a href="geocentric-models.html#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="geocentric-models.html#cb67-4" aria-hidden="true" tabindex="-1"></a>d_grid_samples <span class="sc">%&gt;%</span> </span>
<span id="cb67-5"><a href="geocentric-models.html#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mu, <span class="at">y =</span> sigma)) <span class="sc">+</span></span>
<span id="cb67-6"><a href="geocentric-models.html#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.9</span>, <span class="at">alpha =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb67-7"><a href="geocentric-models.html#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb67-8"><a href="geocentric-models.html#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(mu[samples]),</span>
<span id="cb67-9"><a href="geocentric-models.html#cb67-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="fu">expression</span>(sigma[samples])) <span class="sc">+</span></span>
<span id="cb67-10"><a href="geocentric-models.html#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="geocentric-models.html#cb68-1" aria-hidden="true" tabindex="-1"></a>d_grid_samples <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="geocentric-models.html#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mu, sigma) <span class="sc">%&gt;%</span> </span>
<span id="cb68-3"><a href="geocentric-models.html#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb68-4"><a href="geocentric-models.html#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb68-5"><a href="geocentric-models.html#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">&#39;grey35&#39;</span>, <span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb68-6"><a href="geocentric-models.html#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="cn">NULL</span>, <span class="at">breaks =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb68-7"><a href="geocentric-models.html#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb68-8"><a href="geocentric-models.html#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb68-9"><a href="geocentric-models.html#cb68-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>key, <span class="at">scales =</span> <span class="st">&#39;free&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="geocentric-models.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidybayes)</span></code></pre></div>
<pre><code>## Warning: package &#39;tidybayes&#39; was built under R version 4.1.2</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="geocentric-models.html#cb71-1" aria-hidden="true" tabindex="-1"></a>d_grid_samples <span class="sc">%&gt;%</span> </span>
<span id="cb71-2"><a href="geocentric-models.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mu, sigma) <span class="sc">%&gt;%</span> </span>
<span id="cb71-3"><a href="geocentric-models.html#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb71-4"><a href="geocentric-models.html#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(key) <span class="sc">%&gt;%</span> </span>
<span id="cb71-5"><a href="geocentric-models.html#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mode_hdi</span>(value)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   key    value .lower .upper .width .point .interval
##   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;    
## 1 mu    155.   154.   156.     0.95 mode   hdi      
## 2 sigma   7.75   7.22   8.35   0.95 mode   hdi</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="geocentric-models.html#cb73-1" aria-hidden="true" tabindex="-1"></a>d_grid_samples <span class="sc">%&gt;%</span> </span>
<span id="cb73-2"><a href="geocentric-models.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mu, sigma) <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="geocentric-models.html#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb73-4"><a href="geocentric-models.html#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(key) <span class="sc">%&gt;%</span> </span>
<span id="cb73-5"><a href="geocentric-models.html#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">median_qi</span>(value, <span class="at">.width =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   key    value .lower .upper .width .point .interval
##   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;    
## 1 mu    155.   154.   155.      0.5 median qi       
## 2 sigma   7.77   7.57   7.97    0.5 median qi</code></pre>
</div>
<div id="finding-the-posterior-distribution-with-quap" class="section level3 hasAnchor" number="4.3.5">
<h3><span class="header-section-number">4.3.5</span> Finding the posterior distribution with <code>quap</code><a href="geocentric-models.html#finding-the-posterior-distribution-with-quap" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that <em>quadratic approximation</em> uses the <em>maximum a posteriori</em> (MAP) as the peak of the distribution and creates the shape of the distribution as a negative quadratic based on the slope near the peak.</p>
<p>To set up, lets rerun the data input</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="geocentric-models.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Howell1)</span>
<span id="cb75-2"><a href="geocentric-models.html#cb75-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> Howell1</span>
<span id="cb75-3"><a href="geocentric-models.html#cb75-3" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d[d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span>,]</span></code></pre></div>
<p>Now we have to define our model parameters in R code</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="geocentric-models.html#cb76-1" aria-hidden="true" tabindex="-1"></a>flist <span class="ot">&lt;-</span> <span class="fu">alist</span>(</span>
<span id="cb76-2"><a href="geocentric-models.html#cb76-2" aria-hidden="true" tabindex="-1"></a>height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb76-3"><a href="geocentric-models.html#cb76-3" aria-hidden="true" tabindex="-1"></a>mu <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>),</span>
<span id="cb76-4"><a href="geocentric-models.html#cb76-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>)</span>
<span id="cb76-5"><a href="geocentric-models.html#cb76-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>And then we can fit the model to the data</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="geocentric-models.html#cb77-1" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(flist, <span class="at">data =</span> d2)</span></code></pre></div>
<p>and the posterior is available to view here</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="geocentric-models.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>##             mean        sd       5.5%      94.5%
## mu    154.606930 0.4120200 153.948443 155.265418
## sigma   7.731809 0.2914308   7.266046   8.197571</code></pre>
<p>Changing the prior for <span class="math inline">\(\mu\)</span> to be quite narrow</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="geocentric-models.html#cb80-1" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb80-2"><a href="geocentric-models.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb80-3"><a href="geocentric-models.html#cb80-3" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb80-4"><a href="geocentric-models.html#cb80-4" aria-hidden="true" tabindex="-1"></a>    mu <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="fl">0.1</span>),</span>
<span id="cb80-5"><a href="geocentric-models.html#cb80-5" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>)</span>
<span id="cb80-6"><a href="geocentric-models.html#cb80-6" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d2)</span>
<span id="cb80-7"><a href="geocentric-models.html#cb80-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-8"><a href="geocentric-models.html#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>##            mean        sd      5.5%     94.5%
## mu    177.86375 0.1002354 177.70356 178.02395
## sigma  24.51748 0.9289156  23.03289  26.00207</code></pre>
<p>notice here that because the prior was so narrow for <span class="math inline">\(\mu\)</span>, the mean did not change much from the prior value. <span class="math inline">\(\sigma\)</span> on the other hand has vastly changed from the previous example even though its prior remained the same.</p>
</div>
<div id="sampling-with-quap" class="section level3 hasAnchor" number="4.3.6">
<h3><span class="header-section-number">4.3.6</span> Sampling with <code>quap</code><a href="geocentric-models.html#sampling-with-quap" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Because quadratic approximation is inherently multidimensional, we need to access to the different covariances between pairs of parameters. Here is the variance-covariance matrix for the first model.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="geocentric-models.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(m4<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>##                 mu        sigma
## mu    0.1697604695 0.0002160376
## sigma 0.0002160376 0.0849319320</code></pre>
<p>The above contains both the variance of each parameter but also the correlated change expected in the other parameters. To see them separately:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="geocentric-models.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(<span class="fu">vcov</span>(m4<span class="fl">.1</span>)) <span class="co">#variance of each parameter (sqrt = sd)</span></span></code></pre></div>
<pre><code>##         mu      sigma 
## 0.16976047 0.08493193</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="geocentric-models.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov2cor</span>(<span class="fu">vcov</span>(m4<span class="fl">.1</span>)) <span class="co">#Correlation matrix of the parameters </span></span></code></pre></div>
<pre><code>##                mu       sigma
## mu    1.000000000 0.001799184
## sigma 0.001799184 1.000000000</code></pre>
<p>The correlation matrix above indicates that <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> are very far from correlated. Now let’s pull vectors of values from a multi-dimenstional distribution (made easy with <code>rethinking</code>)</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="geocentric-models.html#cb88-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.1</span>, <span class="at">n =</span> <span class="fl">1e4</span>)</span>
<span id="cb88-2"><a href="geocentric-models.html#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="geocentric-models.html#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(post)</span></code></pre></div>
<pre><code>##         mu    sigma
## 1 154.7748 7.358637
## 2 155.5361 7.869098
## 3 154.4503 7.648488
## 4 154.9172 7.283003
## 5 153.7071 7.978019
## 6 154.6316 8.848559</code></pre>
<p>Now we can compare to the posterior samples to the MAP values</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="geocentric-models.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(post)</span></code></pre></div>
<pre><code>##             mean        sd       5.5%     94.5%    histogram
## mu    154.610172 0.4093737 153.948552 155.26072      ▁▁▅▇▂▁▁
## sigma   7.728621 0.2873045   7.267368   8.18118 ▁▁▁▂▅▇▇▃▁▁▁▁</code></pre>
</div>
</div>
<div id="linear-prediction" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Linear Prediction<a href="geocentric-models.html#linear-prediction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have a model for height, we can get to the ‘regression’ part where we add a <em>predictor variable</em>. Let’s add weight to our height model and see what that looks like</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="geocentric-models.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Howell1); d <span class="ot">&lt;-</span> Howell1; d2 <span class="ot">&lt;-</span> d[d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span>, ]</span>
<span id="cb92-2"><a href="geocentric-models.html#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(d2<span class="sc">$</span>height <span class="sc">~</span> d2<span class="sc">$</span>weight)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.37-1.png" width="672" /></p>
<p>Seems to be a pretty clear relationship between height and weight. The linear model strategy will take the predictor variable (weight) and assume that it has a constant additive relationship to the mean of the outcome (height). Now we have to put our predictor into the model structure.<br />
</p>
<p><span class="math display">\[\begin{equation}
    h_{i} ~ \text{Normal}(\mu_{i}, \sigma)
    \mu_{i} = \beta (x_{i} - \overline{x})
    \alpha ~ \text{Normal}(178, 20)
    \beta ~ \text{Uniform}(0, 10)
    \sigma ~ \text{Uniform}(0, 50)
\end{equation}\]</span></p>
<div id="probability-of-the-data-first-line-of-the-model" class="section level4 hasAnchor" number="4.4.0.1">
<h4><span class="header-section-number">4.4.0.1</span> Probability of the data (first line of the model)<a href="geocentric-models.html#probability-of-the-data-first-line-of-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>So now that both height <span class="math inline">\(h_{i}\)</span> and the mean <span class="math inline">\(\mu_{i}\)</span> are indexed by <span class="math inline">\(i\)</span> it means that each data point or row in the dataframe influences the value of <span class="math inline">\(\mu\)</span> and therefore <span class="math inline">\(h\)</span>.</p>
</div>
<div id="linear-model-second-line-of-the-model" class="section level4 hasAnchor" number="4.4.0.2">
<h4><span class="header-section-number">4.4.0.2</span> Linear model (second line of the model)<a href="geocentric-models.html#linear-model-second-line-of-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The value of <span class="math inline">\(\mu_{i}\)</span> is now made from a combination of <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, and observed weight data (<span class="math inline">\(x\)</span>) where <span class="math inline">\(\overline{x}\)</span> describes the mean of all weight values observed.</p>
<p>There are two parts to this line in the model that make it ‘linear’<br />
1. When <span class="math inline">\(x_{i}\)</span> = <span class="math inline">\(\overline{x}\)</span> then the <span class="math inline">\(\beta\)</span> value is 0 which makes <span class="math inline">\(\alpha\)</span> an ‘intercept.’<br />
2. When <span class="math inline">\(x_{i}\)</span> increases by one unit, the expected change in height (<span class="math inline">\(h_{i}\)</span>) is explained by <span class="math inline">\(\beta\)</span> or the ‘slope.’<br />
</p>
</div>
<div id="priors-lines-3-5-of-the-model" class="section level4 hasAnchor" number="4.4.0.3">
<h4><span class="header-section-number">4.4.0.3</span> Priors (lines 3-5 of the model)<a href="geocentric-models.html#priors-lines-3-5-of-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\sigma\)</span> priors is basically the same as before (except now the <span class="math inline">\(\mu\)</span> prior is now <span class="math inline">\(\alpha\)</span>). The <span class="math inline">\(\beta\)</span> prior is set to have a mean of 0 on purpose because we don’t know for sure what the relationship is between weight and height (even though the plot suggests a positive slope value). To illustrate this point, McElreath simulates the prior predictive distribution using observed weights.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="geocentric-models.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2971</span>)</span>
<span id="cb93-2"><a href="geocentric-models.html#cb93-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="co"># 100 lines</span></span>
<span id="cb93-3"><a href="geocentric-models.html#cb93-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="dv">178</span>, <span class="dv">20</span>) <span class="co"># alpha prior</span></span>
<span id="cb93-4"><a href="geocentric-models.html#cb93-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="dv">0</span>, <span class="dv">10</span>) <span class="co"># beta prior</span></span></code></pre></div>
<p>Let’s see how this random selection from the priors looks</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="geocentric-models.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>, <span class="at">xlim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>, <span class="dv">400</span>),</span>
<span id="cb94-2"><a href="geocentric-models.html#cb94-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&#39;weight&#39;</span>, <span class="at">ylab =</span> <span class="st">&#39;height&#39;</span>)</span>
<span id="cb94-3"><a href="geocentric-models.html#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co">#dashed line at height = 0</span></span>
<span id="cb94-4"><a href="geocentric-models.html#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">272</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="co">#solid line at world&#39;s tallest person</span></span>
<span id="cb94-5"><a href="geocentric-models.html#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&#39;b ~ dnorm(0, 10)&#39;</span>) <span class="co">#plot title</span></span>
<span id="cb94-6"><a href="geocentric-models.html#cb94-6" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(d2<span class="sc">$</span>weight) <span class="co">#average weight</span></span>
<span id="cb94-7"><a href="geocentric-models.html#cb94-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N){</span>
<span id="cb94-8"><a href="geocentric-models.html#cb94-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(a[i] <span class="sc">+</span> b[i]<span class="sc">*</span>(x <span class="sc">-</span> xbar), <span class="co">#linear equation for each pair</span></span>
<span id="cb94-9"><a href="geocentric-models.html#cb94-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">from =</span> <span class="fu">min</span>(d2<span class="sc">$</span>weight), <span class="at">to =</span> <span class="fu">max</span>(d2<span class="sc">$</span>weight), <span class="at">add =</span> <span class="cn">TRUE</span>,</span>
<span id="cb94-10"><a href="geocentric-models.html#cb94-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">col.alpha</span>(<span class="st">&#39;black&#39;</span>,<span class="fl">0.2</span>))</span>
<span id="cb94-11"><a href="geocentric-models.html#cb94-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.39-1.png" width="672" /></p>
<p>This is clearly absurd as no adult should be near 0 height and weigh 30 kg. We can fix this by holding <span class="math inline">\(\beta\)</span> positive with a log-normal distribution</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="geocentric-models.html#cb95-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(<span class="fl">1e4</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb95-2"><a href="geocentric-models.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(b, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>), <span class="at">adj =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.40-1.png" width="672" /></p>
<p>Now we can use this new <span class="math inline">\(\beta\)</span> prior in the last plot</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="geocentric-models.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2971</span>)</span>
<span id="cb96-2"><a href="geocentric-models.html#cb96-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="co"># 100 lines</span></span>
<span id="cb96-3"><a href="geocentric-models.html#cb96-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="dv">178</span>, <span class="dv">20</span>) <span class="co"># alpha prior</span></span>
<span id="cb96-4"><a href="geocentric-models.html#cb96-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(N, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># NEW beta prior</span></span>
<span id="cb96-5"><a href="geocentric-models.html#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="geocentric-models.html#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>, <span class="at">xlim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>, <span class="dv">400</span>),</span>
<span id="cb96-7"><a href="geocentric-models.html#cb96-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&#39;weight&#39;</span>, <span class="at">ylab =</span> <span class="st">&#39;height&#39;</span>)</span>
<span id="cb96-8"><a href="geocentric-models.html#cb96-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="co">#dashed line at height = 0</span></span>
<span id="cb96-9"><a href="geocentric-models.html#cb96-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">272</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="co">#solid line at world&#39;s tallest person</span></span>
<span id="cb96-10"><a href="geocentric-models.html#cb96-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">&#39;log(b) ~ dnorm(0, 1)&#39;</span>) <span class="co">#plot title</span></span>
<span id="cb96-11"><a href="geocentric-models.html#cb96-11" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(d2<span class="sc">$</span>weight) <span class="co">#average weight</span></span>
<span id="cb96-12"><a href="geocentric-models.html#cb96-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N){</span>
<span id="cb96-13"><a href="geocentric-models.html#cb96-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(a[i] <span class="sc">+</span> b[i]<span class="sc">*</span>(x <span class="sc">-</span> xbar), <span class="co">#linear equation for each pair</span></span>
<span id="cb96-14"><a href="geocentric-models.html#cb96-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">from =</span> <span class="fu">min</span>(d2<span class="sc">$</span>weight), <span class="at">to =</span> <span class="fu">max</span>(d2<span class="sc">$</span>weight), <span class="at">add =</span> <span class="cn">TRUE</span>,</span>
<span id="cb96-15"><a href="geocentric-models.html#cb96-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">col.alpha</span>(<span class="st">&#39;black&#39;</span>,<span class="fl">0.2</span>))</span>
<span id="cb96-16"><a href="geocentric-models.html#cb96-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.41-1.png" width="672" /></p>
<p>This new plot seems far more plausible for an adult population.</p>
</div>
<div id="finding-the-posterior-distribtuion" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Finding the posterior distribtuion<a href="geocentric-models.html#finding-the-posterior-distribtuion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just like before we can use the <code>quap</code> function to get a quadratic approximation or alternatively, we can use brms to fit the model.</p>
<p><code>quap</code> method</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="geocentric-models.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#re load the data</span></span>
<span id="cb97-2"><a href="geocentric-models.html#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Howell1) ; d <span class="ot">&lt;-</span> Howell1; d2 <span class="ot">&lt;-</span> d[d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span>,]</span>
<span id="cb97-3"><a href="geocentric-models.html#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="geocentric-models.html#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="co">#define the mean weight of observed values</span></span>
<span id="cb97-5"><a href="geocentric-models.html#cb97-5" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(d2<span class="sc">$</span>weight)</span>
<span id="cb97-6"><a href="geocentric-models.html#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="geocentric-models.html#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="co">#fit the model</span></span>
<span id="cb97-8"><a href="geocentric-models.html#cb97-8" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb97-9"><a href="geocentric-models.html#cb97-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb97-10"><a href="geocentric-models.html#cb97-10" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma), <span class="co">#height likelihood distribution</span></span>
<span id="cb97-11"><a href="geocentric-models.html#cb97-11" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b<span class="sc">*</span>(weight <span class="sc">-</span> xbar), <span class="co">#linear equation</span></span>
<span id="cb97-12"><a href="geocentric-models.html#cb97-12" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>), <span class="co">#alpha prior</span></span>
<span id="cb97-13"><a href="geocentric-models.html#cb97-13" aria-hidden="true" tabindex="-1"></a>    b <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="co">#beta prior</span></span>
<span id="cb97-14"><a href="geocentric-models.html#cb97-14" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>) <span class="co">#sigma prior</span></span>
<span id="cb97-15"><a href="geocentric-models.html#cb97-15" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d2</span>
<span id="cb97-16"><a href="geocentric-models.html#cb97-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb97-17"><a href="geocentric-models.html#cb97-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-18"><a href="geocentric-models.html#cb97-18" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.3</span>)</span></code></pre></div>
<pre><code>##              mean         sd        5.5%       94.5%
## a     154.6013671 0.27030766 154.1693633 155.0333710
## b       0.9032807 0.04192363   0.8362787   0.9702828
## sigma   5.0718809 0.19115478   4.7663786   5.3773831</code></pre>
<p>brms method</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="geocentric-models.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span></code></pre></div>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## Warning: package &#39;Rcpp&#39; was built under R version 4.1.2</code></pre>
<pre><code>## Loading &#39;brms&#39; package (version 2.16.3). Useful instructions
## can be found by typing help(&#39;brms&#39;). A more detailed introduction
## to the package is available through vignette(&#39;brms_overview&#39;).</code></pre>
<pre><code>## 
## Attaching package: &#39;brms&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidybayes&#39;:
## 
##     dstudent_t, pstudent_t, qstudent_t, rstudent_t</code></pre>
<pre><code>## The following objects are masked from &#39;package:rethinking&#39;:
## 
##     LOO, stancode, WAIC</code></pre>
<pre><code>## The following object is masked from &#39;package:rstan&#39;:
## 
##     loo</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     ar</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="geocentric-models.html#cb108-1" aria-hidden="true" tabindex="-1"></a>b4<span class="fl">.3</span>_priors <span class="ot">&lt;-</span> <span class="fu">get_prior</span>(<span class="at">data =</span> d2, <span class="at">formula =</span> height <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> weight)</span>
<span id="cb108-2"><a href="geocentric-models.html#cb108-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-3"><a href="geocentric-models.html#cb108-3" aria-hidden="true" tabindex="-1"></a>b4<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> d2, <span class="co">#data to be used </span></span>
<span id="cb108-4"><a href="geocentric-models.html#cb108-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> gaussian, <span class="co">#likelihood of height</span></span>
<span id="cb108-5"><a href="geocentric-models.html#cb108-5" aria-hidden="true" tabindex="-1"></a>            height <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">+</span> weight, <span class="co">#linear equation</span></span>
<span id="cb108-6"><a href="geocentric-models.html#cb108-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">prior =</span> b4<span class="fl">.3</span>_priors,</span>
<span id="cb108-7"><a href="geocentric-models.html#cb108-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">iter =</span> <span class="dv">41000</span>, <span class="at">warmup =</span> <span class="dv">40000</span>, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">seed =</span> <span class="dv">11</span>) <span class="co">#model mechanics</span></span></code></pre></div>
<pre><code>## Compiling Stan program...</code></pre>
<pre><code>## Trying to compile a simple C file</code></pre>
<pre><code>## Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
## clang -mmacosx-version-min=10.13 -I&quot;/Library/Frameworks/R.framework/Resources/include&quot; -DNDEBUG   -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/unsupported&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/BH/include&quot; -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/src/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppParallel/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rstan/include&quot; -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DBOOST_NO_AUTO_PTR  -include &#39;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp&#39;  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1   -I/usr/local/include   -fPIC  -Wall -g -O2  -c foo.c -o foo.o
## In file included from &lt;built-in&gt;:1:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Dense:1:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Core:88:
## /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:628:1: error: unknown type name &#39;namespace&#39;
## namespace Eigen {
## ^
## /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:628:16: error: expected &#39;;&#39; after top level declarator
## namespace Eigen {
##                ^
##                ;
## In file included from &lt;built-in&gt;:1:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Dense:1:
## /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Core:96:10: fatal error: &#39;complex&#39; file not found
## #include &lt;complex&gt;
##          ^~~~~~~~~
## 3 errors generated.
## make: *** [foo.o] Error 1</code></pre>
<pre><code>## Start sampling</code></pre>
<p>The plot</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="geocentric-models.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(b4<span class="fl">.3</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The alpha values (b_intercept in brms) appear to be quite different here. This is because we haven’t centered the weight values yet (<span class="math inline">\(x - \overline{x}\)</span>), so we can do that and run it again.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="geocentric-models.html#cb114-1" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d2 <span class="sc">%&gt;%</span> </span>
<span id="cb114-2"><a href="geocentric-models.html#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight_c =</span> weight <span class="sc">-</span> <span class="fu">mean</span>(weight))</span>
<span id="cb114-3"><a href="geocentric-models.html#cb114-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-4"><a href="geocentric-models.html#cb114-4" aria-hidden="true" tabindex="-1"></a>b4<span class="fl">.3</span>b_priors <span class="ot">&lt;-</span> <span class="fu">get_prior</span>(<span class="at">data =</span> d2, <span class="at">formula =</span> height <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> weight_c)</span>
<span id="cb114-5"><a href="geocentric-models.html#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="geocentric-models.html#cb114-6" aria-hidden="true" tabindex="-1"></a>b4<span class="fl">.3</span>b <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> d2, <span class="co">#data to be used </span></span>
<span id="cb114-7"><a href="geocentric-models.html#cb114-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> gaussian, <span class="co">#likelihood of height</span></span>
<span id="cb114-8"><a href="geocentric-models.html#cb114-8" aria-hidden="true" tabindex="-1"></a>            height <span class="sc">~</span>  <span class="dv">1</span> <span class="sc">+</span> weight_c, <span class="co">#linear equation</span></span>
<span id="cb114-9"><a href="geocentric-models.html#cb114-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">prior =</span> b4<span class="fl">.3</span>b_priors,</span>
<span id="cb114-10"><a href="geocentric-models.html#cb114-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">iter =</span> <span class="dv">41000</span>, <span class="at">warmup =</span> <span class="dv">40000</span>, <span class="at">chains =</span> <span class="dv">4</span>, <span class="at">cores =</span> <span class="dv">4</span>, <span class="at">seed =</span> <span class="dv">11</span>) <span class="co">#model mechanics</span></span></code></pre></div>
<pre><code>## Compiling Stan program...</code></pre>
<pre><code>## recompiling to avoid crashing R session</code></pre>
<pre><code>## Trying to compile a simple C file</code></pre>
<pre><code>## Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
## clang -mmacosx-version-min=10.13 -I&quot;/Library/Frameworks/R.framework/Resources/include&quot; -DNDEBUG   -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/unsupported&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/BH/include&quot; -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/src/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppParallel/include/&quot;  -I&quot;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rstan/include&quot; -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DBOOST_NO_AUTO_PTR  -include &#39;/Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp&#39;  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1   -I/usr/local/include   -fPIC  -Wall -g -O2  -c foo.c -o foo.o
## In file included from &lt;built-in&gt;:1:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Dense:1:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Core:88:
## /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:628:1: error: unknown type name &#39;namespace&#39;
## namespace Eigen {
## ^
## /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:628:16: error: expected &#39;;&#39; after top level declarator
## namespace Eigen {
##                ^
##                ;
## In file included from &lt;built-in&gt;:1:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13:
## In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Dense:1:
## /Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppEigen/include/Eigen/Core:96:10: fatal error: &#39;complex&#39; file not found
## #include &lt;complex&gt;
##          ^~~~~~~~~
## 3 errors generated.
## make: *** [foo.o] Error 1</code></pre>
<pre><code>## Start sampling</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="geocentric-models.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(b4<span class="fl">.3</span>b)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="interpreting-the-posterior-distribution" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Interpreting the posterior distribution<a href="geocentric-models.html#interpreting-the-posterior-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p><a href="geocentric-models.html#the-model">The model</a> can only report the posterior distribution. This is the right answer to the question you asked. But it’s your responsibility to process the answer and make sense of it.</p>
<p>—McElreath, p.98</p>
</blockquote>
<p>You can make sense of model outputs in two ways:<br />
1. read summary tables<br />
2. plot simulations<br />
</p>
<p>Reading summary tables becomes rather complicated as the models become more complex.</p>
<div id="tables-of-marginal-distributions" class="section level4 hasAnchor" number="4.4.2.1">
<h4><span class="header-section-number">4.4.2.1</span> Tables of marginal distributions<a href="geocentric-models.html#tables-of-marginal-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="geocentric-models.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.3</span>)</span></code></pre></div>
<pre><code>##              mean         sd        5.5%       94.5%
## a     154.6013671 0.27030766 154.1693633 155.0333710
## b       0.9032807 0.04192363   0.8362787   0.9702828
## sigma   5.0718809 0.19115478   4.7663786   5.3773831</code></pre>
<p>In this table, the first row is the quadratic approximation for <span class="math inline">\(\alpha\)</span>, second is <span class="math inline">\(\beta\)</span>, and finally <span class="math inline">\(\sigma\)</span>.</p>
<p>repeated for our brms model</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="geocentric-models.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">posterior_summary</span>(b4<span class="fl">.3</span>b, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.055</span>,<span class="fl">0.945</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,], <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##             Estimate Est.Error   Q5.5  Q94.5
## b_Intercept   154.59      0.27 154.16 155.03
## b_weight_c      0.91      0.04   0.84   0.97
## sigma           5.10      0.19   4.81   5.41</code></pre>
<p>Now let’s see the variance-covariance matrix</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="geocentric-models.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">vcov</span>(m4<span class="fl">.3</span>), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##           a     b sigma
## a     0.073 0.000 0.000
## b     0.000 0.002 0.000
## sigma 0.000 0.000 0.037</code></pre>
<p>repeated for brms model</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="geocentric-models.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">posterior_samples</span>(b4<span class="fl">.3</span>b) <span class="sc">%&gt;%</span> </span>
<span id="cb127-2"><a href="geocentric-models.html#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>lp__) <span class="sc">%&gt;%</span> </span>
<span id="cb127-3"><a href="geocentric-models.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb127-4"><a href="geocentric-models.html#cb127-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Warning: Method &#39;posterior_samples&#39; is deprecated. Please see ?as_draws for
## recommended alternatives.</code></pre>
<pre><code>##             b_Intercept b_weight_c sigma
## b_Intercept        1.00       0.03  0.05
## b_weight_c         0.03       1.00 -0.05
## sigma              0.05      -0.05  1.00</code></pre>
<p>Visual approach</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="geocentric-models.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(m4<span class="fl">.3</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>*very little covariance here</p>
</div>
<div id="plotting-the-posterior-inference-against-the-data" class="section level4 hasAnchor" number="4.4.2.2">
<h4><span class="header-section-number">4.4.2.2</span> Plotting the posterior inference against the data<a href="geocentric-models.html#plotting-the-posterior-inference-against-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="geocentric-models.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, <span class="at">data =</span> d2, <span class="at">col =</span> rangi2) <span class="co">#plot the data points</span></span>
<span id="cb131-2"><a href="geocentric-models.html#cb131-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.3</span>) <span class="co">#extract samples from the posterior</span></span>
<span id="cb131-3"><a href="geocentric-models.html#cb131-3" aria-hidden="true" tabindex="-1"></a>a_map <span class="ot">&lt;-</span> <span class="fu">mean</span>(post<span class="sc">$</span>a) <span class="co">#get the mean of the samples of alpha</span></span>
<span id="cb131-4"><a href="geocentric-models.html#cb131-4" aria-hidden="true" tabindex="-1"></a>b_map <span class="ot">&lt;-</span> <span class="fu">mean</span>(post<span class="sc">$</span>b) <span class="co">#get the mean of the samples of beta</span></span>
<span id="cb131-5"><a href="geocentric-models.html#cb131-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(a_map <span class="sc">+</span> b_map<span class="sc">*</span>(x <span class="sc">-</span> xbar), <span class="at">add =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.46-1.png" width="672" /></p>
<p>This line is very plausible but ther are others that are equally plausible</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="geocentric-models.html#cb132-1" aria-hidden="true" tabindex="-1"></a>d2 <span class="sc">%&gt;%</span> </span>
<span id="cb132-2"><a href="geocentric-models.html#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> weight, <span class="at">y =</span> height)) <span class="sc">+</span></span>
<span id="cb132-3"><a href="geocentric-models.html#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">fixef</span>(b4<span class="fl">.3</span>)[<span class="dv">1</span>], </span>
<span id="cb132-4"><a href="geocentric-models.html#cb132-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">fixef</span>(b4<span class="fl">.3</span>)[<span class="dv">2</span>]) <span class="sc">+</span></span>
<span id="cb132-5"><a href="geocentric-models.html#cb132-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">&#39;royalblue&#39;</span>) <span class="sc">+</span></span>
<span id="cb132-6"><a href="geocentric-models.html#cb132-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb132-7"><a href="geocentric-models.html#cb132-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<div id="adding-uncertainty-around-the-mean" class="section level4 hasAnchor" number="4.4.2.3">
<h4><span class="header-section-number">4.4.2.3</span> Adding uncertainty around the mean<a href="geocentric-models.html#adding-uncertainty-around-the-mean" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are many combinations of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> that could be plausible</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="geocentric-models.html#cb133-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.3</span>)</span>
<span id="cb133-2"><a href="geocentric-models.html#cb133-2" aria-hidden="true" tabindex="-1"></a>post[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,]</span></code></pre></div>
<pre><code>##          a         b    sigma
## 1 154.5881 0.9003425 5.100300
## 2 154.7976 0.8215653 4.910262
## 3 154.2077 0.9884418 5.531922
## 4 154.2817 0.9844592 5.301360
## 5 153.8708 0.8650101 4.828438</code></pre>
<p>We will also alter the amount of observations to see how it influences the spread of these combinations.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="geocentric-models.html#cb135-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co">#lets pull 10 data points</span></span>
<span id="cb135-2"><a href="geocentric-models.html#cb135-2" aria-hidden="true" tabindex="-1"></a>dN <span class="ot">&lt;-</span> d2[<span class="dv">1</span><span class="sc">:</span>N, ]</span>
<span id="cb135-3"><a href="geocentric-models.html#cb135-3" aria-hidden="true" tabindex="-1"></a>mN <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb135-4"><a href="geocentric-models.html#cb135-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb135-5"><a href="geocentric-models.html#cb135-5" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb135-6"><a href="geocentric-models.html#cb135-6" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b<span class="sc">*</span>(weight <span class="sc">-</span> <span class="fu">mean</span>(weight)),</span>
<span id="cb135-7"><a href="geocentric-models.html#cb135-7" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>),</span>
<span id="cb135-8"><a href="geocentric-models.html#cb135-8" aria-hidden="true" tabindex="-1"></a>    b <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb135-9"><a href="geocentric-models.html#cb135-9" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>)</span>
<span id="cb135-10"><a href="geocentric-models.html#cb135-10" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d2)</span></code></pre></div>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="geocentric-models.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co">#and plot 20 samples</span></span>
<span id="cb136-2"><a href="geocentric-models.html#cb136-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(mN, <span class="at">n=</span><span class="dv">20</span>)</span>
<span id="cb136-3"><a href="geocentric-models.html#cb136-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-4"><a href="geocentric-models.html#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="co">#display data and sample size</span></span>
<span id="cb136-5"><a href="geocentric-models.html#cb136-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dN<span class="sc">$</span>weight, dN<span class="sc">$</span>height, <span class="at">xlim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>height),</span>
<span id="cb136-6"><a href="geocentric-models.html#cb136-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> rangi2, <span class="at">xlab =</span> <span class="st">&#39;weight&#39;</span>, <span class="at">ylab =</span> <span class="st">&#39;height&#39;</span>,)</span>
<span id="cb136-7"><a href="geocentric-models.html#cb136-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="fu">concat</span>(<span class="st">&#39;N = &#39;</span>,N))</span>
<span id="cb136-8"><a href="geocentric-models.html#cb136-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-9"><a href="geocentric-models.html#cb136-9" aria-hidden="true" tabindex="-1"></a><span class="co">#add sample lines</span></span>
<span id="cb136-10"><a href="geocentric-models.html#cb136-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>){</span>
<span id="cb136-11"><a href="geocentric-models.html#cb136-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(post<span class="sc">$</span>a[i] <span class="sc">+</span> post<span class="sc">$</span>b[i]<span class="sc">*</span>(x <span class="sc">-</span> <span class="fu">mean</span>(dN<span class="sc">$</span>weight)),</span>
<span id="cb136-12"><a href="geocentric-models.html#cb136-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="fu">col.alpha</span>(<span class="st">&#39;black&#39;</span>,<span class="fl">0.3</span>), <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb136-13"><a href="geocentric-models.html#cb136-13" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.49-1.png" width="672" /></p>
<p>You can see that the extreme weight values are far more spread out. This pattern disappears when the model has more data to work with and becomes more confident about the means.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="geocentric-models.html#cb137-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">300</span> <span class="co">#lets pull 300 data points</span></span>
<span id="cb137-2"><a href="geocentric-models.html#cb137-2" aria-hidden="true" tabindex="-1"></a>dN <span class="ot">&lt;-</span> d2[<span class="dv">1</span><span class="sc">:</span>N, ]</span>
<span id="cb137-3"><a href="geocentric-models.html#cb137-3" aria-hidden="true" tabindex="-1"></a>mN <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb137-4"><a href="geocentric-models.html#cb137-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb137-5"><a href="geocentric-models.html#cb137-5" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb137-6"><a href="geocentric-models.html#cb137-6" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b<span class="sc">*</span>(weight <span class="sc">-</span> <span class="fu">mean</span>(weight)),</span>
<span id="cb137-7"><a href="geocentric-models.html#cb137-7" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>),</span>
<span id="cb137-8"><a href="geocentric-models.html#cb137-8" aria-hidden="true" tabindex="-1"></a>    b <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb137-9"><a href="geocentric-models.html#cb137-9" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>)</span>
<span id="cb137-10"><a href="geocentric-models.html#cb137-10" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d2)</span>
<span id="cb137-11"><a href="geocentric-models.html#cb137-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-12"><a href="geocentric-models.html#cb137-12" aria-hidden="true" tabindex="-1"></a><span class="co">#and plot 20 samples</span></span>
<span id="cb137-13"><a href="geocentric-models.html#cb137-13" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(mN, <span class="at">n=</span><span class="dv">25</span>)</span>
<span id="cb137-14"><a href="geocentric-models.html#cb137-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-15"><a href="geocentric-models.html#cb137-15" aria-hidden="true" tabindex="-1"></a><span class="co">#display data and sample size</span></span>
<span id="cb137-16"><a href="geocentric-models.html#cb137-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dN<span class="sc">$</span>weight, dN<span class="sc">$</span>height, <span class="at">xlim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>height),</span>
<span id="cb137-17"><a href="geocentric-models.html#cb137-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> rangi2, <span class="at">xlab =</span> <span class="st">&#39;weight&#39;</span>, <span class="at">ylab =</span> <span class="st">&#39;height&#39;</span>,)</span>
<span id="cb137-18"><a href="geocentric-models.html#cb137-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="fu">concat</span>(<span class="st">&#39;N = &#39;</span>,N))</span>
<span id="cb137-19"><a href="geocentric-models.html#cb137-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-20"><a href="geocentric-models.html#cb137-20" aria-hidden="true" tabindex="-1"></a><span class="co">#add sample lines</span></span>
<span id="cb137-21"><a href="geocentric-models.html#cb137-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>){</span>
<span id="cb137-22"><a href="geocentric-models.html#cb137-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(post<span class="sc">$</span>a[i] <span class="sc">+</span> post<span class="sc">$</span>b[i]<span class="sc">*</span>(x <span class="sc">-</span> <span class="fu">mean</span>(dN<span class="sc">$</span>weight)),</span>
<span id="cb137-23"><a href="geocentric-models.html#cb137-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="fu">col.alpha</span>(<span class="st">&#39;black&#39;</span>,<span class="fl">0.3</span>), <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb137-24"><a href="geocentric-models.html#cb137-24" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="plotting-regression-intervals-and-contours" class="section level4 hasAnchor" number="4.4.2.4">
<h4><span class="header-section-number">4.4.2.4</span> Plotting regression intervals and contours<a href="geocentric-models.html#plotting-regression-intervals-and-contours" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s use 50 kg as a focal weight and grab some samples</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="geocentric-models.html#cb138-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.3</span>)</span>
<span id="cb138-2"><a href="geocentric-models.html#cb138-2" aria-hidden="true" tabindex="-1"></a>mu_at_50 <span class="ot">&lt;-</span> post<span class="sc">$</span>a <span class="sc">+</span> post<span class="sc">$</span>b <span class="sc">*</span> (<span class="dv">50</span> <span class="sc">-</span> xbar)</span></code></pre></div>
<p>Now we can look at the distribution of plausible heights for a person of 50kg weight</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="geocentric-models.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(mu_at_50, <span class="at">col =</span> rangi2, <span class="at">xlab =</span> <span class="st">&#39;mu|weight = 50kg&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.51-1.png" width="672" /></p>
<p>The height of someone that weighs 50 kg is almost certainly between 158 and 160.5 cm.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="geocentric-models.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(mu_at_50, <span class="at">prob =</span> <span class="fl">0.89</span>)</span></code></pre></div>
<pre><code>##       5%      94% 
## 158.5708 159.6647</code></pre>
<p>and 89% of the ways the model can produce the data suggests that the average height of a 50kg person is between 159 and 160cm.</p>
<p>Now what can we do about the average slope (<span class="math inline">\(\beta\)</span>) from the model?</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="geocentric-models.html#cb142-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.3</span>)</span>
<span id="cb142-2"><a href="geocentric-models.html#cb142-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mu)</span></code></pre></div>
<pre><code>##  num [1:1000, 1:352] 156 157 157 157 158 ...</code></pre>
<p>Now we have a large matrix that has 1000 samples (rows) for 352 data points (observations). But we want to have increments of 1 kg steps across the x axis.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="geocentric-models.html#cb144-1" aria-hidden="true" tabindex="-1"></a>weight.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">25</span>, <span class="at">to =</span> <span class="dv">70</span>, <span class="at">by =</span><span class="dv">1</span>)</span>
<span id="cb144-2"><a href="geocentric-models.html#cb144-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb144-3"><a href="geocentric-models.html#cb144-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.3</span>, <span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">weight =</span> weight.seq))</span>
<span id="cb144-4"><a href="geocentric-models.html#cb144-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mu)</span></code></pre></div>
<pre><code>##  num [1:1000, 1:46] 137 137 137 137 137 ...</code></pre>
<p>Now our new matrix has 1000 samples across 46 weight steps. Let’s visualize the uncertainty of each weight value.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="geocentric-models.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, d2, <span class="at">type =</span> <span class="st">&#39;n&#39;</span>) <span class="co">#type &#39;n&#39; hides the data</span></span>
<span id="cb146-2"><a href="geocentric-models.html#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb146-3"><a href="geocentric-models.html#cb146-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(weight.seq, mu[i,], <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.1</span>))</span>
<span id="cb146-4"><a href="geocentric-models.html#cb146-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.55-1.png" width="672" /></p>
<p>Now we can compute a mean <span class="math inline">\(\mu\)</span> value and the distribution for each weight value</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="geocentric-models.html#cb147-1" aria-hidden="true" tabindex="-1"></a>mu_mean <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, mean)</span>
<span id="cb147-2"><a href="geocentric-models.html#cb147-2" aria-hidden="true" tabindex="-1"></a>mu_PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>)</span></code></pre></div>
<p>And add them to the plot</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="geocentric-models.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, <span class="at">data =</span> d2, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>))</span>
<span id="cb148-2"><a href="geocentric-models.html#cb148-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu_PI, weight.seq, <span class="at">col =</span> <span class="st">&#39;grey80&#39;</span>)</span>
<span id="cb148-3"><a href="geocentric-models.html#cb148-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu_mean)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.57-1.png" width="672" /></p>
</div>
<div id="prediction-intervals" class="section level4 hasAnchor" number="4.4.2.5">
<h4><span class="header-section-number">4.4.2.5</span> Prediction Intervals<a href="geocentric-models.html#prediction-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Now that we have a good handle on <span class="math inline">\(\mu_{i}\)</span> we can combine it with <span class="math inline">\(\sigma\)</span> to create estimates of height rather than just the mean.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="geocentric-models.html#cb149-1" aria-hidden="true" tabindex="-1"></a>sim.height <span class="ot">&lt;-</span> <span class="fu">sim</span>(m4<span class="fl">.3</span>, <span class="at">data =</span> <span class="fu">list</span>(<span class="at">weight =</span> weight.seq))</span>
<span id="cb149-2"><a href="geocentric-models.html#cb149-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sim.height)</span></code></pre></div>
<pre><code>##  num [1:1000, 1:46] 129 137 139 138 132 ...</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="geocentric-models.html#cb151-1" aria-hidden="true" tabindex="-1"></a>height.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim.height, <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>)</span></code></pre></div>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="geocentric-models.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, d2, <span class="at">type =</span> <span class="st">&#39;n&#39;</span>)</span>
<span id="cb152-2"><a href="geocentric-models.html#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(height.PI, weight.seq, <span class="at">col =</span> <span class="st">&#39;grey85&#39;</span>)</span>
<span id="cb152-3"><a href="geocentric-models.html#cb152-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu_PI, weight.seq, <span class="at">col =</span> <span class="st">&#39;grey60&#39;</span>)</span>
<span id="cb152-4"><a href="geocentric-models.html#cb152-4" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> d2<span class="sc">$</span>weight, <span class="at">y =</span> d2<span class="sc">$</span>height, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>))</span>
<span id="cb152-5"><a href="geocentric-models.html#cb152-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-6"><a href="geocentric-models.html#cb152-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu_mean)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.61-1.png" width="672" /></p>
<p><em>Note: shade() seeems to be broken for me in that without specifying a colour, it is completely transparent</em></p>
<p>If you want to smooth the edges of the interval, you can add more samples to the <code>sim.height</code> controls.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="geocentric-models.html#cb153-1" aria-hidden="true" tabindex="-1"></a>sim.height <span class="ot">&lt;-</span> <span class="fu">sim</span>(m4<span class="fl">.3</span>, <span class="at">data=</span><span class="fu">list</span>(<span class="at">weight =</span> weight.seq), <span class="at">n=</span><span class="fl">1e4</span>)</span>
<span id="cb153-2"><a href="geocentric-models.html#cb153-2" aria-hidden="true" tabindex="-1"></a>height.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim.height, <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>)</span>
<span id="cb153-3"><a href="geocentric-models.html#cb153-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-4"><a href="geocentric-models.html#cb153-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, d2, <span class="at">type =</span> <span class="st">&#39;n&#39;</span>)</span>
<span id="cb153-5"><a href="geocentric-models.html#cb153-5" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(height ~ weight, data = d2, col = col.alpha(rangi2, 0.5))</span></span>
<span id="cb153-6"><a href="geocentric-models.html#cb153-6" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(height.PI, weight.seq, <span class="at">col =</span> <span class="st">&#39;grey85&#39;</span>)</span>
<span id="cb153-7"><a href="geocentric-models.html#cb153-7" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu_PI, weight.seq, <span class="at">col =</span> <span class="st">&#39;grey60&#39;</span>)</span>
<span id="cb153-8"><a href="geocentric-models.html#cb153-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> d2<span class="sc">$</span>weight, <span class="at">y =</span> d2<span class="sc">$</span>height, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>))</span>
<span id="cb153-9"><a href="geocentric-models.html#cb153-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu_mean)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.62-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="curves-from-lines" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Curves from lines<a href="geocentric-models.html#curves-from-lines" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are two common methods to build curves from lines. One is <em>Polynomial Regression</em> and the other is <em>B-Splines</em>.</p>
<div id="polynomial-regression" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Polynomial regression<a href="geocentric-models.html#polynomial-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This method uses powers of a variable (squares &amp; cubes) as extra pedictors. Let’s grab all the height and weight data, not just adults.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="geocentric-models.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Howell1)</span>
<span id="cb154-2"><a href="geocentric-models.html#cb154-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> Howell1</span>
<span id="cb154-3"><a href="geocentric-models.html#cb154-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-4"><a href="geocentric-models.html#cb154-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height<span class="sc">~</span>weight, d)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.64-1.png" width="672" /></p>
<p>This is quite the curve. We can try to model it with a parabolic model:<br />
</p>
<p><span class="math display">\[\begin{equation}
\mu_{i} = \alpha + \beta_{1} x_{i} + \beta_{2} x_{i}^{2}
\end{equation}\]</span></p>
<p>where now each weight observation <span class="math inline">\(x_{i}\)</span> is used twice. Once as before as a linear fit and a second time squared to produce the curvature of the line defined as <span class="math inline">\(\beta_{2}\)</span></p>
<p>To fit the model to the data we will need to standardize the predictor variable.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="geocentric-models.html#cb155-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>weight_s <span class="ot">&lt;-</span> (d<span class="sc">$</span>weight <span class="sc">-</span> <span class="fu">mean</span>(d<span class="sc">$</span>weight))<span class="sc">/</span><span class="fu">sd</span>(d<span class="sc">$</span>weight)</span>
<span id="cb155-2"><a href="geocentric-models.html#cb155-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>weight_s2 <span class="ot">&lt;-</span> d<span class="sc">$</span>weight_s<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb155-3"><a href="geocentric-models.html#cb155-3" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb155-4"><a href="geocentric-models.html#cb155-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb155-5"><a href="geocentric-models.html#cb155-5" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma), <span class="co">#same as before</span></span>
<span id="cb155-6"><a href="geocentric-models.html#cb155-6" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b1<span class="sc">*</span>weight_s <span class="sc">+</span> b2<span class="sc">*</span>weight_s2, <span class="co">#adding the b2 and squared term here</span></span>
<span id="cb155-7"><a href="geocentric-models.html#cb155-7" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>), <span class="co">#same</span></span>
<span id="cb155-8"><a href="geocentric-models.html#cb155-8" aria-hidden="true" tabindex="-1"></a>    b1 <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="co">#same as beta prior before</span></span>
<span id="cb155-9"><a href="geocentric-models.html#cb155-9" aria-hidden="true" tabindex="-1"></a>    b2 <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="co">#new prior that could be positive or negative</span></span>
<span id="cb155-10"><a href="geocentric-models.html#cb155-10" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>)</span>
<span id="cb155-11"><a href="geocentric-models.html#cb155-11" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d</span>
<span id="cb155-12"><a href="geocentric-models.html#cb155-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Now try and interpret the results of the summary table</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="geocentric-models.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.5</span>)</span></code></pre></div>
<pre><code>##             mean        sd       5.5%      94.5%
## a     146.057091 0.3690024 145.467354 146.646828
## b1     21.733375 0.2889103  21.271640  22.195109
## b2     -7.802703 0.2742060  -8.240937  -7.364469
## sigma   5.774884 0.1764970   5.492808   6.056960</code></pre>
<p>Not very straight forward how the numbers in the table relate to the data</p>
<p>Let’s find the mean for <span class="math inline">\(\mu\)</span> again now with <span class="math inline">\(\beta_{1}\)</span> and <span class="math inline">\(\beta_{2}\)</span> in the equation.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="geocentric-models.html#cb158-1" aria-hidden="true" tabindex="-1"></a>weight.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="fl">2.2</span>, <span class="at">to =</span> <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">30</span>) <span class="co"># grab 30 equally spaced weight values</span></span>
<span id="cb158-2"><a href="geocentric-models.html#cb158-2" aria-hidden="true" tabindex="-1"></a>pred_dat <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">weight_s =</span> weight.seq, <span class="at">weight_s2 =</span> weight.seq<span class="sc">^</span><span class="dv">2</span>) <span class="co">#new weight values</span></span>
<span id="cb158-3"><a href="geocentric-models.html#cb158-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.5</span>, <span class="at">data =</span> pred_dat) <span class="co">#get new estimates from new data</span></span>
<span id="cb158-4"><a href="geocentric-models.html#cb158-4" aria-hidden="true" tabindex="-1"></a>mu.mean <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, mean) <span class="co">#calculate the mu mean for the line</span></span>
<span id="cb158-5"><a href="geocentric-models.html#cb158-5" aria-hidden="true" tabindex="-1"></a>mu.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu , <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>) <span class="co">#calculate a 89% interval around the mean for mu</span></span>
<span id="cb158-6"><a href="geocentric-models.html#cb158-6" aria-hidden="true" tabindex="-1"></a>sim.height <span class="ot">&lt;-</span> <span class="fu">sim</span>(m4<span class="fl">.5</span>, <span class="at">data =</span> pred_dat) <span class="co">#calculate estimates for heights based on mu and sigma with new weight values</span></span>
<span id="cb158-7"><a href="geocentric-models.html#cb158-7" aria-hidden="true" tabindex="-1"></a>height.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim.height, <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>) <span class="co">#calculate 89% intervals of height</span></span></code></pre></div>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="geocentric-models.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height<span class="sc">~</span>weight_s, d, <span class="at">type =</span> <span class="st">&#39;n&#39;</span>)</span>
<span id="cb159-2"><a href="geocentric-models.html#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu.mean)</span>
<span id="cb159-3"><a href="geocentric-models.html#cb159-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu.PI, weight.seq)</span>
<span id="cb159-4"><a href="geocentric-models.html#cb159-4" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(height.PI, weight.seq)</span>
<span id="cb159-5"><a href="geocentric-models.html#cb159-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> d<span class="sc">$</span>weight_s, <span class="at">y =</span> d<span class="sc">$</span>height, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.68-1.png" width="672" /></p>
<p>Now let’s try adding a cubic predictor term <span class="math inline">\(\beta_{3}x_{i}^3\)</span></p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="geocentric-models.html#cb160-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>weight_s3 <span class="ot">&lt;-</span> d<span class="sc">$</span>weight_s<span class="sc">^</span><span class="dv">3</span></span>
<span id="cb160-2"><a href="geocentric-models.html#cb160-2" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb160-3"><a href="geocentric-models.html#cb160-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb160-4"><a href="geocentric-models.html#cb160-4" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb160-5"><a href="geocentric-models.html#cb160-5" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b1<span class="sc">*</span>weight_s <span class="sc">+</span> b2<span class="sc">*</span>weight_s2 <span class="sc">+</span> b3<span class="sc">*</span>weight_s3,</span>
<span id="cb160-6"><a href="geocentric-models.html#cb160-6" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>),</span>
<span id="cb160-7"><a href="geocentric-models.html#cb160-7" aria-hidden="true" tabindex="-1"></a>    b1 <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb160-8"><a href="geocentric-models.html#cb160-8" aria-hidden="true" tabindex="-1"></a>    b2 <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb160-9"><a href="geocentric-models.html#cb160-9" aria-hidden="true" tabindex="-1"></a>    b3 <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb160-10"><a href="geocentric-models.html#cb160-10" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>, <span class="dv">50</span>)</span>
<span id="cb160-11"><a href="geocentric-models.html#cb160-11" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d</span>
<span id="cb160-12"><a href="geocentric-models.html#cb160-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="geocentric-models.html#cb161-1" aria-hidden="true" tabindex="-1"></a>weight.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="fl">2.2</span>, <span class="at">to =</span> <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">30</span>) <span class="co"># grab 30 equally spaced weight values</span></span>
<span id="cb161-2"><a href="geocentric-models.html#cb161-2" aria-hidden="true" tabindex="-1"></a>pred_dat <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">weight_s =</span> weight.seq, <span class="at">weight_s2 =</span> weight.seq<span class="sc">^</span><span class="dv">2</span>, <span class="at">weight_s3 =</span> weight.seq<span class="sc">^</span><span class="dv">3</span>) <span class="co">#new weight values</span></span>
<span id="cb161-3"><a href="geocentric-models.html#cb161-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.6</span>, <span class="at">data =</span> pred_dat) <span class="co">#get new estimates from new data</span></span>
<span id="cb161-4"><a href="geocentric-models.html#cb161-4" aria-hidden="true" tabindex="-1"></a>mu.mean <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, mean) <span class="co">#calculate the mu mean for the line</span></span>
<span id="cb161-5"><a href="geocentric-models.html#cb161-5" aria-hidden="true" tabindex="-1"></a>mu.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu , <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>) <span class="co">#calculate a 89% interval around the mean for mu</span></span>
<span id="cb161-6"><a href="geocentric-models.html#cb161-6" aria-hidden="true" tabindex="-1"></a>sim.height <span class="ot">&lt;-</span> <span class="fu">sim</span>(m4<span class="fl">.6</span>, <span class="at">data =</span> pred_dat) <span class="co">#calculate estimates for heights based on mu and sigma with new weight values</span></span>
<span id="cb161-7"><a href="geocentric-models.html#cb161-7" aria-hidden="true" tabindex="-1"></a>height.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(sim.height, <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.89</span>) <span class="co">#calculate 89% intervals of height</span></span></code></pre></div>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="geocentric-models.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height<span class="sc">~</span>weight_s, d, <span class="at">type =</span> <span class="st">&#39;n&#39;</span>)</span>
<span id="cb162-2"><a href="geocentric-models.html#cb162-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu.mean)</span>
<span id="cb162-3"><a href="geocentric-models.html#cb162-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu.PI, weight.seq)</span>
<span id="cb162-4"><a href="geocentric-models.html#cb162-4" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(height.PI, weight.seq)</span>
<span id="cb162-5"><a href="geocentric-models.html#cb162-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> d<span class="sc">$</span>weight_s, <span class="at">y =</span> d<span class="sc">$</span>height, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>And here is how you would plot the above with the original x-axis</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="geocentric-models.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight_s, d, <span class="at">col=</span><span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>),  <span class="at">type =</span> <span class="st">&#39;n&#39;</span>, <span class="at">xaxt =</span> <span class="st">&#39;n&#39;</span>) <span class="co">#turn off x axis text</span></span>
<span id="cb163-2"><a href="geocentric-models.html#cb163-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Rcode 4.71</span></span>
<span id="cb163-3"><a href="geocentric-models.html#cb163-3" aria-hidden="true" tabindex="-1"></a>at <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb163-4"><a href="geocentric-models.html#cb163-4" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> at<span class="sc">*</span><span class="fu">sd</span>(d<span class="sc">$</span>weight) <span class="sc">+</span> <span class="fu">mean</span>(d<span class="sc">$</span>weight)</span>
<span id="cb163-5"><a href="geocentric-models.html#cb163-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> at, <span class="at">labels =</span> <span class="fu">round</span>(labels, <span class="dv">1</span>))</span>
<span id="cb163-6"><a href="geocentric-models.html#cb163-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu.mean)</span>
<span id="cb163-7"><a href="geocentric-models.html#cb163-7" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu.PI, weight.seq)</span>
<span id="cb163-8"><a href="geocentric-models.html#cb163-8" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(height.PI, weight.seq)</span>
<span id="cb163-9"><a href="geocentric-models.html#cb163-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> d<span class="sc">$</span>weight_s, <span class="at">y =</span> d<span class="sc">$</span>height, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.70-1.png" width="672" /></p>
</div>
<div id="splines" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Splines<a href="geocentric-models.html#splines" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Splines are smooth functions that are built from smaller component functions that usually take on a wiggly appearance.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="geocentric-models.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load cherry blossom bloom time over a thousand years</span></span>
<span id="cb164-2"><a href="geocentric-models.html#cb164-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rethinking)</span>
<span id="cb164-3"><a href="geocentric-models.html#cb164-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cherry_blossoms)</span>
<span id="cb164-4"><a href="geocentric-models.html#cb164-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> cherry_blossoms</span>
<span id="cb164-5"><a href="geocentric-models.html#cb164-5" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(d)</span></code></pre></div>
<pre><code>##                   mean          sd      5.5%      94.5%       histogram
## year       1408.000000 350.8845964 867.77000 1948.23000   ▇▇▇▇▇▇▇▇▇▇▇▇▁
## doy         104.540508   6.4070362  94.43000  115.00000        ▁▂▅▇▇▃▁▁
## temp          6.141886   0.6636479   5.15000    7.29470        ▁▃▅▇▃▂▁▁
## temp_upper    7.185151   0.9929206   5.89765    8.90235 ▁▂▅▇▇▅▂▂▁▁▁▁▁▁▁
## temp_lower    5.098941   0.8503496   3.78765    6.37000 ▁▁▁▁▁▁▁▃▅▇▃▂▁▁▁</code></pre>
<p>Let’s see the bloom time over the years</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="geocentric-models.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>d<span class="sc">$</span>year, <span class="at">y=</span>d<span class="sc">$</span>doy)</span>
<span id="cb166-2"><a href="geocentric-models.html#cb166-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(d<span class="sc">$</span>doy, <span class="at">na.rm =</span> T), <span class="at">col =</span> <span class="st">&#39;red&#39;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Similar to the polynomial method, B-splines will break the predictor (year) into chunks with different basis functions to fit the data in that chunk. When we stitch the chunks together, we often get a wiggly line through the data.</p>
<p>The new linear function for <span class="math inline">\(\mu_{i}\)</span> will look a bit different.<br />
</p>
<p><span class="math display">\[\begin{equation}
\mu_{i} = \alpha + w_{1}\beta_{i,1} + w_{2}\beta_{i,2} + w_{3}\beta_{i,3} + ...
\end{equation}\]</span></p>
<p>Here, the <span class="math inline">\(\beta\)</span> values are for each basis function and the <span class="math inline">\(w\)</span> parameters are the weights for each function.</p>
<p>For the cherry blossom data we will split the data up into 15 quantiles and have the basis functions operate within each quantile.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="geocentric-models.html#cb167-1" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d[<span class="fu">complete.cases</span>(d<span class="sc">$</span>doy), ] <span class="co">#remove any NA values</span></span>
<span id="cb167-2"><a href="geocentric-models.html#cb167-2" aria-hidden="true" tabindex="-1"></a>num_knots <span class="ot">&lt;-</span> <span class="dv">15</span> <span class="co">#number of sections in the data</span></span>
<span id="cb167-3"><a href="geocentric-models.html#cb167-3" aria-hidden="true" tabindex="-1"></a>knot_list <span class="ot">&lt;-</span> <span class="fu">quantile</span>(d2<span class="sc">$</span>year, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> num_knots))</span>
<span id="cb167-4"><a href="geocentric-models.html#cb167-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb167-5"><a href="geocentric-models.html#cb167-5" aria-hidden="true" tabindex="-1"></a>knot_list</span></code></pre></div>
<pre><code>##        0% 7.142857% 14.28571% 21.42857% 28.57143% 35.71429% 42.85714%       50% 
##       812      1036      1174      1269      1377      1454      1518      1583 
## 57.14286% 64.28571% 71.42857% 78.57143% 85.71429% 92.85714%      100% 
##      1650      1714      1774      1833      1893      1956      2015</code></pre>
<p>So now that we have the break points in the year range of the data we can assign a polynomial degree. This degree determines how many basis functions will be interacting in each year range. If we choose a cubic spline, four basis functions will be active in each year range.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="geocentric-models.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb169-2"><a href="geocentric-models.html#cb169-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">bs</span>(d2<span class="sc">$</span>year, <span class="at">knots =</span> knot_list[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,num_knots)], <span class="at">degree =</span> <span class="dv">3</span>, <span class="at">intercept =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>We just created a matrix that contains 827 rows and 17 columns. Each row is a year in <code>d2</code> and each column is a basis function. Let’s see what it looks like (fig 4.13a)</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="geocentric-models.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>, <span class="at">xlim =</span> <span class="fu">range</span>(d2<span class="sc">$</span>year), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">&#39;year&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;basis&#39;</span>)</span>
<span id="cb170-2"><a href="geocentric-models.html#cb170-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(B)){</span>
<span id="cb170-3"><a href="geocentric-models.html#cb170-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(d2<span class="sc">$</span>year, B[,i])</span>
<span id="cb170-4"><a href="geocentric-models.html#cb170-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb170-5"><a href="geocentric-models.html#cb170-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> knot_list, <span class="at">y =</span> <span class="fu">rep</span>(<span class="fl">0.9</span>, <span class="fu">length</span>(knot_list)), <span class="at">col =</span> <span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.75-1.png" width="672" /></p>
<p>Now we need to calculate the parameter weights (<span class="math inline">\(w\)</span>) for each basis function. To do this we need to run the model.</p>
<p><span class="math display">\[\begin{equation}
D_{i} \sim \text{Normal}(\mu_{i},\sigma)
\mu_{i} = \alpha + \sum_{k=1}^{K}w_{k}B_{k,i}
\alpha \sim \text{Normal}(100,10)
w_{j} \sim \text{Normal}(0,10)
\sigma \sim \text{Exponential}(1)
\end{equation}\]</span></p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="geocentric-models.html#cb171-1" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.7</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb171-2"><a href="geocentric-models.html#cb171-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb171-3"><a href="geocentric-models.html#cb171-3" aria-hidden="true" tabindex="-1"></a>    D <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb171-4"><a href="geocentric-models.html#cb171-4" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> B <span class="sc">%*%</span> w,</span>
<span id="cb171-5"><a href="geocentric-models.html#cb171-5" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">100</span>, <span class="dv">10</span>),</span>
<span id="cb171-6"><a href="geocentric-models.html#cb171-6" aria-hidden="true" tabindex="-1"></a>    w <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb171-7"><a href="geocentric-models.html#cb171-7" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dexp</span>(<span class="dv">1</span>)</span>
<span id="cb171-8"><a href="geocentric-models.html#cb171-8" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> <span class="fu">list</span>(<span class="at">D =</span> d2<span class="sc">$</span>doy, <span class="at">B=</span>B),</span>
<span id="cb171-9"><a href="geocentric-models.html#cb171-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="fu">list</span>(<span class="at">w=</span><span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(B)))</span>
<span id="cb171-10"><a href="geocentric-models.html#cb171-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Now we can extract some samples and look at the basis weights (fig 4.13b)</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="geocentric-models.html#cb172-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.7</span>)</span>
<span id="cb172-2"><a href="geocentric-models.html#cb172-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">apply</span>(post<span class="sc">$</span>w, <span class="dv">2</span>, mean)</span>
<span id="cb172-3"><a href="geocentric-models.html#cb172-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>, <span class="at">xlim=</span><span class="fu">range</span>(d2<span class="sc">$</span>year), <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">6</span>,<span class="dv">6</span>), <span class="at">xlab =</span> <span class="st">&#39;year&#39;</span>, <span class="at">ylab=</span><span class="st">&#39;basis * weight&#39;</span>)</span>
<span id="cb172-4"><a href="geocentric-models.html#cb172-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(B)){</span>
<span id="cb172-5"><a href="geocentric-models.html#cb172-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(d2<span class="sc">$</span>year, w[i]<span class="sc">*</span>B[,i])</span>
<span id="cb172-6"><a href="geocentric-models.html#cb172-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb172-7"><a href="geocentric-models.html#cb172-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="at">x =</span> knot_list, <span class="at">y =</span> <span class="fu">rep</span>(<span class="fl">4.9</span>, <span class="fu">length</span>(knot_list)), <span class="at">col =</span> <span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.77-1.png" width="672" /></p>
<p>Now we can calculate a posterior interval for <span class="math inline">\(\mu\)</span> at each year (fig 4.13c)</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="geocentric-models.html#cb173-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.7</span>)</span>
<span id="cb173-2"><a href="geocentric-models.html#cb173-2" aria-hidden="true" tabindex="-1"></a>mu_PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, PI, <span class="at">prob =</span> <span class="fl">0.97</span>)</span>
<span id="cb173-3"><a href="geocentric-models.html#cb173-3" aria-hidden="true" tabindex="-1"></a>mu_mean <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, mean)</span>
<span id="cb173-4"><a href="geocentric-models.html#cb173-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(d2<span class="sc">$</span>year, d2<span class="sc">$</span>doy, <span class="at">col =</span> <span class="fu">col.alpha</span>(rangi2, <span class="fl">0.3</span>), <span class="at">pch =</span> <span class="dv">16</span>)</span>
<span id="cb173-5"><a href="geocentric-models.html#cb173-5" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu_PI, d2<span class="sc">$</span>year, <span class="at">col =</span> <span class="fu">col.alpha</span>(<span class="st">&#39;black&#39;</span>,<span class="fl">0.5</span>))</span>
<span id="cb173-6"><a href="geocentric-models.html#cb173-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(d2<span class="sc">$</span>year, mu_mean)</span></code></pre></div>
<p><img src="_main_files/figure-html/Rcode%204.78-1.png" width="672" /></p>
<p>A whole other class of similar models are called <em>GAMs</em> (Generalized Additive Models) and are worth looking into if you have time.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sampling-the-imaginary.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-many-variables-the-spurious-waffles.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-parts.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
